project:
  type: website
  output-dir: docs
  execute-dir: project
  resources:
    - images/**
    - OR568_ML_Project/shared-notebooks/data/**

website:
  title: "Flight Delays: A Machine Learning Approach"
  site-url: https://jonathanwilsonami.github.io/OR568_ML_Project/
  repo-url: https://github.com/jonathanwilsonami/OR568_ML_Project

  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About"
      - href: paper.qmd
        text: "Paper"
      - href: ml-pipeline.qmd
        text: "ML Pipeline"
      - href: slides.qmd
        text: "Slides"
      - href: shared-notebooks/index.qmd
        text: "Shared Notebooks"

  sidebar:
  - id: shared-notebooks
    title: "Shared Notebooks"
    style: docked
    search: true
    contents:
      - shared-notebooks/index.qmd

      - section: "Jon"
        contents: "shared-notebooks/notebooks/jon/**/*"

      - section: "Karan"
        contents: "shared-notebooks/notebooks/karan/**/*"

      - section: "Irena"
        contents: "shared-notebooks/notebooks/irena/**/*"

      - section: "Val"
        contents: "shared-notebooks/notebooks/val/**/*"

format:
  html:
    theme: cyborg
    css: styles.css
    toc: true
    include-in-header:
      - text: |
          <link rel="stylesheet"
                href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

bibliography: references.bib
csl: https://www.zotero.org/styles/ieee