name: or568_ml_project
channels:
  - conda-forge
  - defaults
dependencies:
  - nb_conda_kernels
  - r-data.table
  - r-skimr
  - scikit-learn
  - r-broom
  - r-here
  - r-igraph
  - jupytext
  - r-xgboost
  - xgboost
  - r-tidyverse
  - r-pacman
  - matplotlib
  - pandas
  - r-base=4.3
  - scipy
  - lightgbm
  - r-glmnet
  - fastparquet
  - pyarrow
  - r-caret
  - pip
  - seaborn
  - r-irkernel
  - r-kableextra
  - r-tidygraph
  - r-ggraph
  - r-knitr
  - ipykernel
  - jupyterlab
  - r-ranger
  - python=3.11
  - numpy
  - statsmodels
  - r-arrow
  - r-janitor
  - r-rmarkdown
  - r-lubridate
  - polars
