name: or568_ml_project
channels:
  - conda-forge
  - defaults
dependencies:
  - fastparquet
  - pyarrow
  - r-xgboost
  - r-tidyverse
  - r-ggraph
  - r-data.table
  - r-janitor
  - statsmodels
  - r-here
  - r-arrow
  - xgboost
  - python=3.11
  - jupyterlab
  - pandas
  - tensorflow
  - networkx
  - r-vip
  - scikit-learn
  - nb_conda_kernels
  - polars
  - r-rmarkdown
  - r-broom
  - r-tidygraph
  - r-pacman
  - jupytext
  - matplotlib
  - r-caret
  - scipy
  - numpy
  - lightgbm
  - r-skimr
  - r-lubridate
  - seaborn
  - ipykernel
  - r-irkernel
  - r-base=4.3.3
  - r-ranger
  - r-kableextra
  - pip
  - r-glmnet
  - r-knitr
  - r-igraph
  - r-reticulate
