name: or568_ml_project
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip

  # Notebook / kernels
  - jupyterlab
  - jupytext
  - ipykernel
  - nb_conda_kernels

  # Python analytics / ML
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn
  - statsmodels
  - pyarrow
  - fastparquet
  - lightgbm
  - xgboost

  # R base / notebook support
  - r-base=4.3
  - r-irkernel
  - r-knitr
  - r-rmarkdown

  # R data / modeling
  - r-tidyverse
  - r-arrow
  - r-caret
  - r-data.table
  - r-ranger
  - r-xgboost
  - r-ggraph
  - r-igraph
  - r-tidygraph
  - r-broom
  - r-glmnet
  - r-here
  - r-janitor
  - r-kableextra
  - r-lubridate
  - r-skimr
  - r-pacman