<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-03-13">

<title>From Prediction to Digital Twin: A Propagation-Aware Machine Learning Framework for Flight Delay Modeling – Flight Delays: A Machine Learning Approach</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-f418161beb48e0141c760e455f12af2c.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-8b9b450fba28b21070ed4f8d6716e9d1.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Flight Delays: A Machine Learning Approach</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./paper.html" aria-current="page"> 
<span class="menu-text">Paper</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-ml-workflow" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">ML Workflow</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-ml-workflow">    
        <li>
    <a class="dropdown-item" href="./ml_workflow/workflow-intro.html">
 <span class="dropdown-text">ML Worflow Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./ml_workflow/bwi-ny.html">
 <span class="dropdown-text">BWI–NY Market Pair</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./ml_workflow/us-network.html">
 <span class="dropdown-text">U.S. Domestic Network</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="./aero-flux.html"> 
<span class="menu-text">Aero Flux</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction-background" id="toc-introduction-background" class="nav-link active" data-scroll-target="#introduction-background"><span class="header-section-number">1</span> Introduction &amp; Background</a>
  <ul class="collapse">
  <li><a href="#motivation" id="toc-motivation" class="nav-link" data-scroll-target="#motivation"><span class="header-section-number">1.1</span> Motivation</a></li>
  <li><a href="#related-works" id="toc-related-works" class="nav-link" data-scroll-target="#related-works"><span class="header-section-number">1.2</span> Related Works</a>
  <ul class="collapse">
  <li><a href="#time-of-day-impacts" id="toc-time-of-day-impacts" class="nav-link" data-scroll-target="#time-of-day-impacts"><span class="header-section-number">1.2.1</span> Time of Day Impacts</a></li>
  <li><a href="#delay-propagation" id="toc-delay-propagation" class="nav-link" data-scroll-target="#delay-propagation"><span class="header-section-number">1.2.2</span> Delay Propagation</a></li>
  <li><a href="#quick-survey-of-common-flight-delay-models" id="toc-quick-survey-of-common-flight-delay-models" class="nav-link" data-scroll-target="#quick-survey-of-common-flight-delay-models"><span class="header-section-number">1.2.3</span> Quick Survey of Common Flight Delay Models</a></li>
  <li><a href="#digital-twins-and-real-time-monitoring" id="toc-digital-twins-and-real-time-monitoring" class="nav-link" data-scroll-target="#digital-twins-and-real-time-monitoring"><span class="header-section-number">1.2.4</span> Digital Twins and Real-Time Monitoring</a></li>
  </ul></li>
  <li><a href="#research-questions" id="toc-research-questions" class="nav-link" data-scroll-target="#research-questions"><span class="header-section-number">1.3</span> Research Questions</a></li>
  <li><a href="#what-this-research-contributes" id="toc-what-this-research-contributes" class="nav-link" data-scroll-target="#what-this-research-contributes"><span class="header-section-number">1.4</span> What This Research Contributes</a></li>
  </ul></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data"><span class="header-section-number">2</span> Data</a>
  <ul class="collapse">
  <li><a href="#data-sources-pipeline" id="toc-data-sources-pipeline" class="nav-link" data-scroll-target="#data-sources-pipeline"><span class="header-section-number">2.1</span> Data Sources &amp; Pipeline</a>
  <ul class="collapse">
  <li><a href="#data-pipeline" id="toc-data-pipeline" class="nav-link" data-scroll-target="#data-pipeline"><span class="header-section-number">2.1.1</span> Data Pipeline</a></li>
  <li><a href="#data-sources-methods" id="toc-data-sources-methods" class="nav-link" data-scroll-target="#data-sources-methods"><span class="header-section-number">2.1.2</span> Data Sources &amp; Methods</a></li>
  <li><a href="#ingestion" id="toc-ingestion" class="nav-link" data-scroll-target="#ingestion"><span class="header-section-number">2.1.3</span> Ingestion</a></li>
  <li><a href="#cleaning-and-normalization" id="toc-cleaning-and-normalization" class="nav-link" data-scroll-target="#cleaning-and-normalization"><span class="header-section-number">2.1.4</span> Cleaning and normalization</a></li>
  <li><a href="#timestamp-alignment-and-temporal-join" id="toc-timestamp-alignment-and-temporal-join" class="nav-link" data-scroll-target="#timestamp-alignment-and-temporal-join"><span class="header-section-number">2.1.5</span> Timestamp alignment and temporal join</a></li>
  <li><a href="#feature-engineering" id="toc-feature-engineering" class="nav-link" data-scroll-target="#feature-engineering"><span class="header-section-number">2.1.6</span> Feature engineering</a></li>
  <li><a href="#postprocessing-and-output" id="toc-postprocessing-and-output" class="nav-link" data-scroll-target="#postprocessing-and-output"><span class="header-section-number">2.1.7</span> Postprocessing and output</a></li>
  </ul></li>
  <li><a href="#prediction-targets" id="toc-prediction-targets" class="nav-link" data-scroll-target="#prediction-targets"><span class="header-section-number">2.2</span> Prediction Targets</a>
  <ul class="collapse">
  <li><a href="#raw-predictors-and-important-data-elements" id="toc-raw-predictors-and-important-data-elements" class="nav-link" data-scroll-target="#raw-predictors-and-important-data-elements"><span class="header-section-number">2.2.1</span> Raw Predictors and Important Data Elements</a></li>
  </ul></li>
  <li><a href="#limitations-in-data" id="toc-limitations-in-data" class="nav-link" data-scroll-target="#limitations-in-data"><span class="header-section-number">2.3</span> Limitations in Data</a></li>
  <li><a href="#initially-started-with-a-bwiewr-market-pair" id="toc-initially-started-with-a-bwiewr-market-pair" class="nav-link" data-scroll-target="#initially-started-with-a-bwiewr-market-pair"><span class="header-section-number">2.4</span> Initially started with a BWI–EWR Market Pair</a></li>
  </ul></li>
  <li><a href="#eda" id="toc-eda" class="nav-link" data-scroll-target="#eda"><span class="header-section-number">3</span> EDA</a>
  <ul class="collapse">
  <li><a href="#distribution-of-delays" id="toc-distribution-of-delays" class="nav-link" data-scroll-target="#distribution-of-delays"><span class="header-section-number">3.1</span> Distribution of Delays</a></li>
  <li><a href="#delays-by-time-of-day" id="toc-delays-by-time-of-day" class="nav-link" data-scroll-target="#delays-by-time-of-day"><span class="header-section-number">3.2</span> Delays by Time of Day</a></li>
  <li><a href="#weather-vs-delay" id="toc-weather-vs-delay" class="nav-link" data-scroll-target="#weather-vs-delay"><span class="header-section-number">3.3</span> Weather vs Delay</a></li>
  <li><a href="#delay-propagation-1" id="toc-delay-propagation-1" class="nav-link" data-scroll-target="#delay-propagation-1"><span class="header-section-number">3.4</span> Delay Propagation</a></li>
  <li><a href="#centrality-metrics" id="toc-centrality-metrics" class="nav-link" data-scroll-target="#centrality-metrics"><span class="header-section-number">3.5</span> Centrality Metrics</a></li>
  </ul></li>
  <li><a href="#models" id="toc-models" class="nav-link" data-scroll-target="#models"><span class="header-section-number">4</span> Models</a>
  <ul class="collapse">
  <li><a href="#phase-1-2019-baseline" id="toc-phase-1-2019-baseline" class="nav-link" data-scroll-target="#phase-1-2019-baseline"><span class="header-section-number">4.1</span> Phase 1: 2019 Baseline</a>
  <ul class="collapse">
  <li><a href="#logistic-regression" id="toc-logistic-regression" class="nav-link" data-scroll-target="#logistic-regression"><span class="header-section-number">4.1.1</span> Logistic Regression</a></li>
  <li><a href="#ridge-logistic-regression" id="toc-ridge-logistic-regression" class="nav-link" data-scroll-target="#ridge-logistic-regression"><span class="header-section-number">4.1.2</span> Ridge Logistic Regression</a></li>
  <li><a href="#basic-decision-trees" id="toc-basic-decision-trees" class="nav-link" data-scroll-target="#basic-decision-trees"><span class="header-section-number">4.1.3</span> Basic Decision Trees</a></li>
  <li><a href="#random-forest" id="toc-random-forest" class="nav-link" data-scroll-target="#random-forest"><span class="header-section-number">4.1.4</span> Random Forest</a></li>
  <li><a href="#k-nearest-neighbors" id="toc-k-nearest-neighbors" class="nav-link" data-scroll-target="#k-nearest-neighbors"><span class="header-section-number">4.1.5</span> K-Nearest Neighbors</a></li>
  <li><a href="#unsupervised-analysis-principal-component-analysis" id="toc-unsupervised-analysis-principal-component-analysis" class="nav-link" data-scroll-target="#unsupervised-analysis-principal-component-analysis"><span class="header-section-number">4.1.6</span> Unsupervised Analysis: Principal Component Analysis</a></li>
  <li><a href="#unsupervised-analysis-k-means-clustering" id="toc-unsupervised-analysis-k-means-clustering" class="nav-link" data-scroll-target="#unsupervised-analysis-k-means-clustering"><span class="header-section-number">4.1.7</span> Unsupervised Analysis: K-Means Clustering</a></li>
  </ul></li>
  <li><a href="#phase-2-multi-year" id="toc-phase-2-multi-year" class="nav-link" data-scroll-target="#phase-2-multi-year"><span class="header-section-number">4.2</span> Phase 2: Multi Year</a>
  <ul class="collapse">
  <li><a href="#hardware" id="toc-hardware" class="nav-link" data-scroll-target="#hardware"><span class="header-section-number">4.2.1</span> Hardware</a></li>
  <li><a href="#lstm-spatio-temporal-model" id="toc-lstm-spatio-temporal-model" class="nav-link" data-scroll-target="#lstm-spatio-temporal-model"><span class="header-section-number">4.2.2</span> LSTM Spatio-Temporal Model</a></li>
  <li><a href="#xgboost" id="toc-xgboost" class="nav-link" data-scroll-target="#xgboost"><span class="header-section-number">4.2.3</span> XGBoost</a></li>
  <li><a href="#xgboost-classification-model" id="toc-xgboost-classification-model" class="nav-link" data-scroll-target="#xgboost-classification-model"><span class="header-section-number">4.2.4</span> XGBoost Classification Model</a></li>
  <li><a href="#xgboost-regression-model" id="toc-xgboost-regression-model" class="nav-link" data-scroll-target="#xgboost-regression-model"><span class="header-section-number">4.2.5</span> XGBoost Regression Model</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#model-evaluation-metrics-comparitive-perfromance" id="toc-model-evaluation-metrics-comparitive-perfromance" class="nav-link" data-scroll-target="#model-evaluation-metrics-comparitive-perfromance"><span class="header-section-number">5</span> Model Evaluation Metrics &amp; Comparitive Perfromance</a>
  <ul class="collapse">
  <li><a href="#ml-pipeline" id="toc-ml-pipeline" class="nav-link" data-scroll-target="#ml-pipeline"><span class="header-section-number">5.1</span> ML Pipeline</a></li>
  <li><a href="#time-aware-cross-validation" id="toc-time-aware-cross-validation" class="nav-link" data-scroll-target="#time-aware-cross-validation"><span class="header-section-number">5.2</span> Time-Aware Cross Validation</a></li>
  <li><a href="#hyperparameter-search" id="toc-hyperparameter-search" class="nav-link" data-scroll-target="#hyperparameter-search"><span class="header-section-number">5.3</span> Hyperparameter Search</a>
  <ul class="collapse">
  <li><a href="#candidate-configurations" id="toc-candidate-configurations" class="nav-link" data-scroll-target="#candidate-configurations"><span class="header-section-number">5.3.1</span> Candidate Configurations</a></li>
  <li><a href="#selected-configuration" id="toc-selected-configuration" class="nav-link" data-scroll-target="#selected-configuration"><span class="header-section-number">5.3.2</span> Selected Configuration</a></li>
  </ul></li>
  <li><a href="#cross-validation-performance" id="toc-cross-validation-performance" class="nav-link" data-scroll-target="#cross-validation-performance"><span class="header-section-number">5.4</span> Cross-Validation Performance</a>
  <ul class="collapse">
  <li><a href="#classification-performance-mean-across-5-folds" id="toc-classification-performance-mean-across-5-folds" class="nav-link" data-scroll-target="#classification-performance-mean-across-5-folds"><span class="header-section-number">5.4.1</span> Classification Performance (Mean Across 5 Folds)</a></li>
  <li><a href="#regression-performance-mean-across-5-folds" id="toc-regression-performance-mean-across-5-folds" class="nav-link" data-scroll-target="#regression-performance-mean-across-5-folds"><span class="header-section-number">5.4.2</span> Regression Performance (Mean Across 5 Folds)</a></li>
  <li><a href="#interpretation-of-cross-validation-stability" id="toc-interpretation-of-cross-validation-stability" class="nav-link" data-scroll-target="#interpretation-of-cross-validation-stability"><span class="header-section-number">5.4.3</span> Interpretation of Cross-Validation Stability</a></li>
  </ul></li>
  <li><a href="#final-refit-and-holdout-evaluation" id="toc-final-refit-and-holdout-evaluation" class="nav-link" data-scroll-target="#final-refit-and-holdout-evaluation"><span class="header-section-number">5.5</span> Final Refit and Holdout Evaluation</a>
  <ul class="collapse">
  <li><a href="#refit-procedure" id="toc-refit-procedure" class="nav-link" data-scroll-target="#refit-procedure"><span class="header-section-number">5.5.1</span> Refit Procedure</a></li>
  <li><a href="#final-holdout-test-results-2025---post-tuning" id="toc-final-holdout-test-results-2025---post-tuning" class="nav-link" data-scroll-target="#final-holdout-test-results-2025---post-tuning"><span class="header-section-number">5.5.2</span> Final Holdout Test Results (2025) - Post Tuning</a></li>
  <li><a href="#interpretation-of-final-results" id="toc-interpretation-of-final-results" class="nav-link" data-scroll-target="#interpretation-of-final-results"><span class="header-section-number">5.5.3</span> Interpretation of Final Results</a></li>
  </ul></li>
  <li><a href="#feature-importance-analysis" id="toc-feature-importance-analysis" class="nav-link" data-scroll-target="#feature-importance-analysis"><span class="header-section-number">5.6</span> Feature Importance Analysis</a></li>
  <li><a href="#feature-set-comparison" id="toc-feature-set-comparison" class="nav-link" data-scroll-target="#feature-set-comparison"><span class="header-section-number">5.7</span> Feature Set Comparison</a></li>
  <li><a href="#computational-performance" id="toc-computational-performance" class="nav-link" data-scroll-target="#computational-performance"><span class="header-section-number">5.8</span> Computational Performance</a></li>
  <li><a href="#model-comparison" id="toc-model-comparison" class="nav-link" data-scroll-target="#model-comparison"><span class="header-section-number">5.9</span> Model Comparison</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">5.10</span> Summary</a></li>
  <li><a href="#operational-impact" id="toc-operational-impact" class="nav-link" data-scroll-target="#operational-impact"><span class="header-section-number">5.11</span> Operational Impact</a></li>
  <li><a href="#model-limitations" id="toc-model-limitations" class="nav-link" data-scroll-target="#model-limitations"><span class="header-section-number">5.12</span> Model Limitations</a></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion"><span class="header-section-number">6</span> Discussion</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">7</span> Conclusion</a></li>
  <li><a href="#appendex" id="toc-appendex" class="nav-link" data-scroll-target="#appendex"><span class="header-section-number">8</span> Appendex</a>
  <ul class="collapse">
  <li><a href="#introduction-to-aeroflux-real-time-inference-for-flight-delay-prediction" id="toc-introduction-to-aeroflux-real-time-inference-for-flight-delay-prediction" class="nav-link" data-scroll-target="#introduction-to-aeroflux-real-time-inference-for-flight-delay-prediction"><span class="header-section-number">8.1</span> Introduction to AeroFlux: Real-Time Inference for Flight Delay Prediction</a>
  <ul class="collapse">
  <li><a href="#aeroflux-is-the-precursor-to-a-digital-twin" id="toc-aeroflux-is-the-precursor-to-a-digital-twin" class="nav-link" data-scroll-target="#aeroflux-is-the-precursor-to-a-digital-twin"><span class="header-section-number">8.1.1</span> AeroFlux is the precursor to a digital twin</a></li>
  </ul></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="paper.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">From Prediction to Digital Twin: A Propagation-Aware Machine Learning Framework for Flight Delay Modeling</h1>
  <div class="quarto-categories">
    <div class="quarto-category">Machine Learning</div>
    <div class="quarto-category">Aviation</div>
    <div class="quarto-category">Flight Delays</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Authors</div>
    <div class="quarto-title-meta-contents">
             <p>Jonathan Wilson </p>
             <p>Karan Nindra </p>
             <p>Irena Austin </p>
             <p>Val Sokolow </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 13, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="callout callout-style-simple callout-note no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>Abstract</p>
<p>Flight delays remain a persistent challenge in modern aviation, driven by complex interactions between weather, operations, and network dynamics. This study presents a propagation-aware machine learning framework that models delays as a function of upstream aircraft state rather than isolated flight events. Using large-scale U.S. flight data (~70 million records) enriched with weather and operational features, we construct a two-hop aircraft rotation representation that captures delay carryover across consecutive legs.</p>
<p>We evaluate multiple modeling approaches, including gradient-boosted trees and sequence-based neural networks, under strict time-aware validation to ensure production realism. Results show that upstream delay propagation is the dominant predictive signal, with tree-based models achieving strong performance while remaining computationally efficient at scale.</p>
<p>Beyond prediction, this work establishes the foundation for AeroFlux, a real-time, network-aware system designed to evolve into a digital twin of the U.S. air transportation system, enabling forward simulation and proactive disruption management.</p>
</div>
</div>
</div>
<hr>
<section id="introduction-background" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introduction &amp; Background</h1>
<section id="motivation" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="motivation"><span class="header-section-number">1.1</span> Motivation</h2>
<p>Flight delays represent one of the most visible and persistent operational challenges in modern aviation. In 2025 alone, nearly 25% of U.S. domestic flights failed to arrive on time, marking one of the worst on-time performance levels in over a decade <span class="citation" data-cites="usafacts_ontime"><a href="#ref-usafacts_ontime" role="doc-biblioref">[1]</a></span>. At scale, these disruptions impose significant societal and economic costs—U.S. travelers collectively lost over 1.5 million hours (171 years) waiting on delayed flights <span class="citation" data-cites="people_delayed_airline"><a href="#ref-people_delayed_airline" role="doc-biblioref">[2]</a></span>, while delays across global air travel totaled millions of hours annually <span class="citation" data-cites="skyrefund_ustravel"><a href="#ref-skyrefund_ustravel" role="doc-biblioref">[3]</a></span>.</p>
<p>A single disruption rarely remains isolated. Instead, delays propagate through tightly coupled airline operations, affecting aircraft rotations, crew assignments, passenger connections, and airport congestion. Empirical studies of the U.S. air transportation network show that primary delays—caused by weather, congestion, or operational issues—can cascade and amplify across the network, leading to systemic disruptions that impact a significant portion of flights <span class="citation" data-cites="Fleurquin_2013"><a href="#ref-Fleurquin_2013" role="doc-biblioref">[4]</a></span>. More recent research further demonstrates that accurately modeling delay propagation and absorption dynamics is essential for improving prediction performance and operational resilience <span class="citation" data-cites="zhou2025integratingdelayabsorptioncapabilityflight"><a href="#ref-zhou2025integratingdelayabsorptioncapabilityflight" role="doc-biblioref">[5]</a></span>.</p>
<p>Understanding the mechanisms of delay propagation is therefore critical for improving airline efficiency, reducing operational costs, and enhancing passenger reliability. As air traffic demand continues to grow and systems become increasingly interconnected, the ability to model and predict these cascading effects represents a key challenge—and opportunity—for modern aviation analytics.</p>
</section>
<section id="related-works" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="related-works"><span class="header-section-number">1.2</span> Related Works</h2>
<p>This work introduces a propagation-aware machine learning framework that models flight delays as a function of upstream aircraft state rather than isolated events. By incorporating a two-hop aircraft rotation structure, enforcing strict pre-departure feature availability, and training on multi-year, large-scale data (~70M flights), the approach produces both operationally realistic and high-performing predictions. It further serves as the foundation for AeroFlux, a system designed to evolve from static prediction into a real-time, network-aware digital twin of the U.S. airspace.</p>
<section id="time-of-day-impacts" class="level3" data-number="1.2.1">
<h3 data-number="1.2.1" class="anchored" data-anchor-id="time-of-day-impacts"><span class="header-section-number">1.2.1</span> Time of Day Impacts</h3>
<p>Flight delays exhibit strong temporal patterns, with peak congestion typically occurring during morning and evening “banking” periods at major hubs. Studies using Bureau of Transportation Statistics data consistently show that delays increase throughout the day due to cumulative disruption effects and reduced recovery buffers <span class="citation" data-cites="bts_ontime"><a href="#ref-bts_ontime" role="doc-biblioref">[6]</a></span>. Prior work in transportation analytics confirms that departure time is one of the most statistically significant predictors of delay due to its correlation with demand surges and network congestion <span class="citation" data-cites="rebollo2014predictability"><a href="#ref-rebollo2014predictability" role="doc-biblioref">[7]</a></span>.</p>
</section>
<section id="delay-propagation" class="level3" data-number="1.2.2">
<h3 data-number="1.2.2" class="anchored" data-anchor-id="delay-propagation"><span class="header-section-number">1.2.2</span> Delay Propagation</h3>
<p>Delay propagation has been widely studied as a network phenomenon where disruptions spread through aircraft rotations and airport interactions. Foundational work by <span class="citation" data-cites="Fleurquin_2013"><a href="#ref-Fleurquin_2013" role="doc-biblioref">[4]</a></span> demonstrates that primary delays can cascade across the U.S. air transportation network, amplifying system-wide disruption. Subsequent research modeled these dynamics using complex network theory, showing how disruptions propagate through tightly coupled flight schedules <span class="citation" data-cites="li2016delay"><a href="#ref-li2016delay" role="doc-biblioref">[8]</a></span>. More recent work highlights that incorporating upstream flight state — including delay absorption capacity at intermediate airports — significantly improves predictive performance, reinforcing the importance of modeling propagation dynamics explicitly <span class="citation" data-cites="zhou2025integratingdelayabsorptioncapabilityflight"><a href="#ref-zhou2025integratingdelayabsorptioncapabilityflight" role="doc-biblioref">[5]</a></span>.</p>
</section>
<section id="quick-survey-of-common-flight-delay-models" class="level3" data-number="1.2.3">
<h3 data-number="1.2.3" class="anchored" data-anchor-id="quick-survey-of-common-flight-delay-models"><span class="header-section-number">1.2.3</span> Quick Survey of Common Flight Delay Models</h3>
<p>Machine learning approaches to flight delay prediction commonly include tree-based models such as XGBoost and deep learning models such as Long Short-Term Memory (LSTM) networks. XGBoost, introduced by <span class="citation" data-cites="chen2016xgboost"><a href="#ref-chen2016xgboost" role="doc-biblioref">[9]</a></span>, is widely favored for large-scale tabular data due to its strong performance, interpretability, and computational efficiency. LSTMs <span class="citation" data-cites="hochreiter1997lstm"><a href="#ref-hochreiter1997lstm" role="doc-biblioref">[10]</a></span> are used to capture temporal dependencies across sequential flight events, making them a natural fit for rotation-chain modeling. Benchmark evaluations on structured tabular data consistently show that tree-based ensembles remain state-of-the-art over deep learning models, with deep learning offering advantages primarily when temporal or graph-based relationships are explicitly modeled <span class="citation" data-cites="grinsztajn2022tree"><a href="#ref-grinsztajn2022tree" role="doc-biblioref">[11]</a></span>.</p>
<p>More recent work has explored advanced architectures including Graph Neural Networks (GNNs) for modeling airport connectivity and network effects <span class="citation" data-cites="zhao2020gnn_airtraffic"><a href="#ref-zhao2020gnn_airtraffic" role="doc-biblioref">[12]</a></span>, Spatio-Temporal Graph Convolutional Networks (ST-GCN) for capturing joint spatial and temporal dependencies <span class="citation" data-cites="yu2018stgcn"><a href="#ref-yu2018stgcn" role="doc-biblioref">[13]</a></span>, Transformer-based sequence models applied to air traffic trajectory and flow prediction <span class="citation" data-cites="vos2024transformer_airtraffic airtraffic_transformer_flow"><a href="#ref-vos2024transformer_airtraffic" role="doc-biblioref">[14]</a>, <a href="#ref-airtraffic_transformer_flow" role="doc-biblioref">[15]</a></span>, and attention-based multi-agent models for capturing interactions in air traffic systems <span class="citation" data-cites="yoon2025maiformer"><a href="#ref-yoon2025maiformer" role="doc-biblioref">[16]</a></span>.</p>
</section>
<section id="digital-twins-and-real-time-monitoring" class="level3" data-number="1.2.4">
<h3 data-number="1.2.4" class="anchored" data-anchor-id="digital-twins-and-real-time-monitoring"><span class="header-section-number">1.2.4</span> Digital Twins and Real-Time Monitoring</h3>
<p>Digital twins in aviation aim to create continuously updated virtual representations of physical systems for monitoring and simulation. Foundational frameworks in digital twin design emphasize the integration of live telemetry, predictive modeling, and simulation as the basis for proactive decision-making in complex physical systems <span class="citation" data-cites="tao2019digitaltwin fuller2020digital"><a href="#ref-tao2019digitaltwin" role="doc-biblioref">[17]</a>, <a href="#ref-fuller2020digital" role="doc-biblioref">[18]</a></span>. In the aviation domain, the Federal Aviation Administration’s System Wide Information Management (SWIM) program represents a significant step toward real-time data integration for air traffic management and disruption response <span class="citation" data-cites="faa_swim"><a href="#ref-faa_swim" role="doc-biblioref">[19]</a></span>. Recent work in cyber-physical systems reinforces that this combination of live data and predictive intelligence forms the foundation for next-generation intelligent transportation systems — a direction that directly motivates the AeroFlux architecture described in this paper.</p>
<p>Several operational systems now demonstrate this capability in practice. NASA Ames has developed a Digital Twin Simulator of the National Airspace System (NAS) that creates a virtual copy of the live NAS, ingesting real-time SWIM data to enable side-by-side simulation of proposed changes against actual operations <span class="citation" data-cites="nasa_nas_twin"><a href="#ref-nasa_nas_twin" role="doc-biblioref">[20]</a></span>. At the industry level, Airspace Intelligence’s Flyways AI platform applies a 4D airspace simulation built on live FAA SWIM feeds to predict demand-capacity imbalances and recommend optimized traffic management initiatives before disruptions materialize <span class="citation" data-cites="asi_flyways"><a href="#ref-asi_flyways" role="doc-biblioref">[21]</a></span>. Similarly, Mosaic ATM’s Alternate Route Availability Tool (ARAT), developed in collaboration with NASA, integrates real-time weather and TMI data with machine learning models to provide actionable alternate routing recommendations for air traffic controllers <span class="citation" data-cites="mosaicatm_arat"><a href="#ref-mosaicatm_arat" role="doc-biblioref">[22]</a></span>. In the research literature, Liu et al. demonstrate an L3-level airport digital twin for flight ground service delay diagnosis that connects real-time operational data to simulation, enabling timely identification and propagation analysis of delays that offline models cannot achieve <span class="citation" data-cites="liu2024digitaltwin"><a href="#ref-liu2024digitaltwin" role="doc-biblioref">[23]</a></span>.</p>
<p>Recent work in cyber-physical systems reinforces that this combination of live data and predictive intelligence forms the foundation for next-generation intelligent transportation systems — a direction that directly motivates the AeroFlux architecture described in this paper.</p>
</section>
</section>
<section id="research-questions" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="research-questions"><span class="header-section-number">1.3</span> Research Questions</h2>
<p>This study seeks to answer the following questions:</p>
<ol type="1">
<li>To what extent does upstream aircraft delay propagation influence downstream flight delay outcomes?</li>
<li>Which features — including operational, weather, and network-based variables — provide the strongest predictive signal under realistic pre-departure constraints?</li>
<li>How do different machine learning approaches (tree-based vs.&nbsp;sequence-based) perform on large-scale, temporally structured aviation data?</li>
<li>Can a propagation-aware modeling framework serve as a foundation for real-time, network-level prediction and simulation systems in aviation?</li>
</ol>
</section>
<section id="what-this-research-contributes" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="what-this-research-contributes"><span class="header-section-number">1.4</span> What This Research Contributes</h2>
<p>This research contributes a propagation-aware machine learning framework for flight delay prediction that explicitly models delay transmission across aircraft rotations. By introducing a two-hop representation of upstream flight state and enforcing strict pre-departure feature availability, the approach captures the operational dynamics underlying delay formation while remaining suitable for real-world deployment.</p>
<p>The study demonstrates the effectiveness of this framework at scale, training and evaluating models on approximately 70 million U.S. flight records using time-aware validation. Results show that delay propagation is the dominant predictive signal, significantly outperforming models that treat flights independently.</p>
<p>Beyond predictive performance, this work establishes the architectural foundation for AeroFlux — a real-time, network-aware system designed to evolve into a digital twin of the national airspace, enabling forward simulation, disruption propagation analysis, and proactive operational decision-making.</p>
<p>The ultimate objective of this work is to move beyond static prediction and toward dynamic, system-level reasoning in aviation operations. By combining propagation-aware modeling with real-time data integration and simulation capabilities, this research aims to enable predictive intelligence systems that can anticipate, propagate, and mitigate disruptions across the air transportation network. This vision is realized through AeroFlux, which represents a step toward a fully operational digital twin of the U.S. airspace.</p>
</section>
</section>
<section id="data" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Data</h1>
<section id="data-sources-pipeline" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="data-sources-pipeline"><span class="header-section-number">2.1</span> Data Sources &amp; Pipeline</h2>
<section id="data-pipeline" class="level3" data-number="2.1.1">
<h3 data-number="2.1.1" class="anchored" data-anchor-id="data-pipeline"><span class="header-section-number">2.1.1</span> Data Pipeline</h3>
<p>The pipeline integrates three independent data streams — Bureau of Transportation Statistics (BTS) on-time performance records, NOAA Global Surface Hourly weather observations, and airport reference dimensions — into a single analytical dataset suitable for delay prediction modelling. <a href="#fig-pipeline" class="quarto-xref">Figure&nbsp;1</a> provides a schematic overview of each stage. The sections below describe each stage in turn.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-pipeline" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A flowchart showing seven stages of the flight delay pipeline: data sources, ingestion, cleaning and normalisation, timestamp alignment and join, feature engineering, postprocessing, and output.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pipeline-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/common_site/data-pipeline.png" class="img-fluid figure-img" style="width:100.0%" alt="A flowchart showing seven stages of the flight delay pipeline: data sources, ingestion, cleaning and normalisation, timestamp alignment and join, feature engineering, postprocessing, and output.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pipeline-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Overview of the flight delay data pipeline, from raw data sources through ingestion, cleaning, temporal alignment, feature engineering, and final output.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="data-sources-methods" class="level3" data-number="2.1.2">
<h3 data-number="2.1.2" class="anchored" data-anchor-id="data-sources-methods"><span class="header-section-number">2.1.2</span> Data Sources &amp; Methods</h3>
<p>Flight performance data are sourced from the BTS Transtats PREZIP endpoint, which publishes monthly on-time reporting files for all US carriers. Weather observations are obtained from the NOAA National Centers for Environmental Information (NCEI) global-hourly dataset via a REST API, providing sub-hourly surface measurements at reporting stations worldwide. Airport and station reference data are drawn from the OurAirports CSV registry and the NOAA Integrated Surface Database (ISD) station history file, which together supply the geographic coordinates and ICAO codes required to link flight records to their corresponding weather stations.</p>
<p>The primary data sources for this project were:</p>
<ul>
<li><p>The Bureau of Transportation Statistics (BTS) Airline On-Time Performance dataset and the National Oceanic and Atmospheric Administration (NOAA) National Centers for Environmental Information (NCEI) global hourly weather dataset <span class="citation" data-cites="bts_ontime noaa_ncei"><a href="#ref-bts_ontime" role="doc-biblioref">[6]</a>, <a href="#ref-noaa_ncei" role="doc-biblioref">[24]</a></span>.</p></li>
<li><p>To support geospatial alignment between flights and environmental conditions, additional metadata sources were incorporated, including the NOAA Integrated Surface Database (ISD) station history dataset for weather station metadata and the OurAirports global airport dataset for airport identifiers and geographic coordinates <span class="citation" data-cites="noaa_isd_history ourairports"><a href="#ref-noaa_isd_history" role="doc-biblioref">[25]</a>, <a href="#ref-ourairports" role="doc-biblioref">[26]</a></span>.</p></li>
</ul>
<p>The data pipeline also relied on auxiliary airport and station reference data to connect flights to airport metadata, time zones, and weather stations. The overall pipeline included BTS ingestion, airport and station reference construction, weather ingestion, temporal and spatial joins, and downstream feature engineering. These stages were implemented as a modular, cached pipeline to support reproducibility and scalable re-runs.</p>
<p>The BTS data provided detailed flight-level operational records for 2019, including scheduled and actual departure and arrival times, origin and destination airports, carrier information, delay durations, cancellation indicators, diversion indicators, taxi times, and delay-cause variables. The NOAA weather data provided airport-associated weather observations such as temperature, wind speed, wind direction, and ceiling height, which were joined to flights using a backward-looking as-of temporal join.</p>
<p>Aircraft registry variables from the FAA were initially considered. However, because only a 2025 registry snapshot was available while the operational flight data represented 2019 activity, these variables were excluded from the final predictive analysis to avoid temporal inconsistency and possible bias.</p>
<section id="data-source-resource-links" class="level4" data-number="2.1.2.1">
<h4 data-number="2.1.2.1" class="anchored" data-anchor-id="data-source-resource-links"><span class="header-section-number">2.1.2.1</span> Data Source Resource Links</h4>
<p>The pipeline draws on four publicly available data sources, summarised in <a href="#tbl-sources" class="quarto-xref">Table&nbsp;1</a>. All sources are freely accessible and updated on a regular basis.</p>
<div class="cell">
<div id="tbl-sources" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-sources-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Primary data sources used in the flight delay pipeline.
</figcaption>
<div aria-describedby="tbl-sources-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Source</th>
<th style="text-align: left;">Description</th>
<th style="text-align: left;">URL</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">BTS Transtats — On-Time Performance</td>
<td style="text-align: left;">Monthly carrier on-time performance records; the primary source of flight departure, arrival, and delay data.</td>
<td style="text-align: left;"><a href="https://www.transtats.bts.gov/DL_SelectFields.aspx?gnoyr_VQ=FGJ&amp;QO_fu146_anzr=b0-gvzr">transtats.bts.gov</a></td>
</tr>
<tr class="even">
<td style="text-align: left;">BTS Transtats — On-Time Overview</td>
<td style="text-align: left;">Landing page for the BTS on-time reporting programme, including data documentation and field descriptions.</td>
<td style="text-align: left;"><a href="https://www.transtats.bts.gov/ontime/">transtats.bts.gov/ontime</a></td>
</tr>
<tr class="odd">
<td style="text-align: left;">NOAA NCEI — Integrated Surface Database (ISD)</td>
<td style="text-align: left;">Global hourly surface weather observations compiled from over 100 sources, spanning 1901 to present across more than 14,000 active stations.</td>
<td style="text-align: left;"><a href="https://www.ncei.noaa.gov/products/land-based-station/integrated-surface-database">ncei.noaa.gov/products/land-based-station/integrated-surface-database</a></td>
</tr>
<tr class="even">
<td style="text-align: left;">NOAA NCEI — Global Hourly data search</td>
<td style="text-align: left;">Interactive and programmatic access to the NCEI global-hourly subset, supporting station search and date-range subsetting.</td>
<td style="text-align: left;"><a href="https://www.ncei.noaa.gov/access/search/data-search/global-hourly">ncei.noaa.gov/access/search/data-search/global-hourly</a></td>
</tr>
<tr class="odd">
<td style="text-align: left;">OurAirports — Open data downloads</td>
<td style="text-align: left;">Open-data download page for airport reference files, including airports.csv with IATA/ICAO codes, coordinates, and metadata.</td>
<td style="text-align: left;"><a href="https://ourairports.com/data/">ourairports.com/data</a></td>
</tr>
<tr class="even">
<td style="text-align: left;">OurAirports — GitHub repository</td>
<td style="text-align: left;">GitHub-hosted daily data dumps for all OurAirports CSV files; the canonical source since November 2021.</td>
<td style="text-align: left;"><a href="https://github.com/davidmegginson/ourairports-data">github.com/davidmegginson/ourairports-data</a></td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
</section>
<section id="ingestion" class="level3" data-number="2.1.3">
<h3 data-number="2.1.3" class="anchored" data-anchor-id="ingestion"><span class="header-section-number">2.1.3</span> Ingestion</h3>
<p>Each data stream is ingested independently. BTS monthly ZIP archives are downloaded with exponential backoff, extracted, and parsed into Polars DataFrames with explicit schema inference and null handling before being serialised to Parquet. Weather records are retrieved in station-month chunks of 25 stations per request, returned as JSON, and similarly persisted to monthly Parquet cache files. Airport and station reference data are loaded from CSV and held in memory as dimension tables. Caching intermediate outputs at this stage is deliberate: it decouples the computationally expensive download and format-conversion steps from all downstream transformations, allowing the pipeline to be re-run from clean intermediates without re-fetching raw data.</p>
</section>
<section id="cleaning-and-normalization" class="level3" data-number="2.1.4">
<h3 data-number="2.1.4" class="anchored" data-anchor-id="cleaning-and-normalization"><span class="header-section-number">2.1.4</span> Cleaning and normalization</h3>
<p>Flight records are filtered to a defined route universe — a set of core airport pairs plus permissible two-hop connections — and deduplicated. Weather records undergo field-level parsing to extract temperature (<code>TMP</code>), wind speed and direction (<code>WND</code>), and ceiling height (<code>CIG</code>) from their packed NOAA format representations; observations with missing values across all primary meteorological fields are dropped. On the reference side, each airport in the BTS route universe is matched to its best-candidate ISD weather station using a nearest-neighbour procedure over geodetic distance, with timezone resolution falling back to a longitude-based estimate where the <code>timezonefinder</code> library cannot resolve a canonical IANA zone.</p>
</section>
<section id="timestamp-alignment-and-temporal-join" class="level3" data-number="2.1.5">
<h3 data-number="2.1.5" class="anchored" data-anchor-id="timestamp-alignment-and-temporal-join"><span class="header-section-number">2.1.5</span> Timestamp alignment and temporal join</h3>
<p>Correct temporal alignment between flight records and weather observations is the most consequential step in the pipeline, and the one most susceptible to subtle error. Flight departure and arrival times in BTS data are recorded in <strong>local airport time</strong> as four-digit integers (HHMM), with no timezone annotation and a known edge case at midnight where the integer representation rolls over incorrectly. These are first converted to timezone-aware datetimes using the IANA timezone resolved for each airport, then projected to <strong>UTC</strong> by applying <code>ZoneInfo</code>-based offsets. Weather observations from NOAA are similarly recorded in station-local time; these are converted to UTC using station-level timezone mappings derived from the reference dimension stage.</p>
<p>Once both datasets share a common UTC timeline, flight records are joined to weather observations using an <strong>as-of join</strong>: for each departure or arrival event, the most recent weather observation at the corresponding station that precedes the event time is selected. This approach correctly handles the irregular and variable cadence of surface weather reporting — stations do not report on a fixed schedule, and naive equi-joins on rounded timestamps would systematically introduce look-ahead bias or large temporal gaps. Separate as-of joins are performed for the origin station at departure time and the destination station at arrival time, yielding paired meteorological conditions for both endpoints of every flight.</p>
<p>Failure to handle timezones rigorously at this stage would propagate systematic errors through all downstream features. A one-hour offset error at a UTC−5 airport, for example, would cause the as-of join to select weather observations from the wrong side of a frontal passage, corrupting both the meteorological predictors and any propagation-chain features that depend on accurate sequencing of events.</p>
</section>
<section id="feature-engineering" class="level3" data-number="2.1.6">
<h3 data-number="2.1.6" class="anchored" data-anchor-id="feature-engineering"><span class="header-section-number">2.1.6</span> Feature engineering</h3>
<p>Three families of derived features are constructed from the aligned dataset. <strong>Flight-level features</strong> include a unique flight identifier constructed from carrier, tail number, origin, destination, and scheduled departure time; aircraft rotation sequences linking successive legs flown by the same tail number; and the standard BTS delay component breakdown (carrier, weather, NAS, security, late aircraft). <strong>Airport-level features</strong> aggregate traffic volume and delay rates within configurable time windows around each departure, capturing congestion dynamics at both origin and destination. <strong>Route-level features</strong> encode delay propagation along rotation chains: a late-aircraft delay on an inbound leg is explicitly linked to the downstream departure it constrains, allowing the model to condition on upstream disruption state.</p>
<p>A <strong>two-hop flight</strong> represents a single aircraft operating two consecutive legs on the same day, connected by a turnaround at an intermediate airport. When the first leg arrives late, the delayed aircraft becomes the inbound for the second leg, compressing or eliminating the scheduled ground time and propagating the delay forward. <a href="#fig-two-hop" class="quarto-xref">Figure&nbsp;2</a> illustrates this for tail N471AA operating BOS → ATL → MIA: a 52-minute departure delay on Leg 1 carries through the ATL turnaround and manifests as a 49-minute departure delay on Leg 2, despite no adverse weather at ATL. This propagation mechanism is captured in the dataset through the <code>prev_arr_late_15</code> and <code>rotation_continuity_flag</code> columns, which allow the model to condition on upstream disruption state when predicting downstream delays.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-two-hop" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Diagram showing two flight legs sharing a tail number, with delay columns, weather as-of joins, and a propagation arrow connecting the delay on the first leg to the second.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-two-hop-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/paper/2hop-clean.png" class="img-fluid figure-img" style="width:100.0%" alt="Diagram showing two flight legs sharing a tail number, with delay columns, weather as-of joins, and a propagation arrow connecting the delay on the first leg to the second.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-two-hop-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Two-hop delay propagation for tail N471AA (BOS → ATL → MIA, 2024-03-15). A 52-minute departure delay on Leg 1 propagates to a 49-minute delay on Leg 2 via the tail rotation, independent of weather conditions at the intermediate airport.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Turnaround time captures the buffer between flights:</p>
<p><span class="math display">\[
Turnaround_i = DepartureTime_i - PreviousArrivalTime_i
\]</span></p>
<p>See <a href="#tbl-predictors" class="quarto-xref">Table&nbsp;2</a> for more information on engineered features.</p>
</section>
<section id="postprocessing-and-output" class="level3" data-number="2.1.7">
<h3 data-number="2.1.7" class="anchored" data-anchor-id="postprocessing-and-output"><span class="header-section-number">2.1.7</span> Postprocessing and output</h3>
<p>A <code>PostProcessConfig</code> object specifies the column subset retained for modelling, allowing the full engineered dataset to be filtered to task-specific representations without rerunning upstream stages. Final outputs are written as monthly and annual Parquet files containing the joined flight-weather records, alongside separate Parquet tables for the canonical flight records, airport-time aggregates, route-time aggregates, aircraft rotation sequences, and delay propagation chains.</p>
</section>
</section>
<section id="prediction-targets" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="prediction-targets"><span class="header-section-number">2.2</span> Prediction Targets</h2>
<p>We considered flight delay prediction as both a regression and classification problem. Let</p>
<p><span class="math display">\[
Y_i^{(reg)} = \text{ArrDelay}_i
\]</span></p>
<p>denote the arrival delay in minutes for flight <span class="math inline">\(i\)</span>, and let</p>
<p><span class="math display">\[
Y_i^{(cls)} =
\begin{cases}
1 &amp; \text{if } \text{ArrDel15}_i = 1 \\
0 &amp; \text{otherwise}
\end{cases}
\]</span></p>
<p>denote whether the flight arrived at least 15 minutes late.</p>
<p>Thus, our predictive tasks were:</p>
<ol type="1">
<li><strong>Regression:</strong> predict continuous arrival delay in minutes.</li>
<li><strong>Classification:</strong> predict whether a flight experiences a material arrival delay.</li>
</ol>
<section id="raw-predictors-and-important-data-elements" class="level3" data-number="2.2.1">
<h3 data-number="2.2.1" class="anchored" data-anchor-id="raw-predictors-and-important-data-elements"><span class="header-section-number">2.2.1</span> Raw Predictors and Important Data Elements</h3>
<p>Table <a href="#tbl-predictors" class="quarto-xref">Table&nbsp;2</a> summarizes the major predictors and supporting data elements used in the pipeline.</p>
<div id="tbl-predictors" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-predictors-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Major predictors and important data items used in the flight delay pipeline.
</figcaption>
<div aria-describedby="tbl-predictors-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Category</th>
<th style="text-align: left;">Variables / Data Items</th>
<th style="text-align: left;">Description and Role in Modeling</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Flight identifiers and route</td>
<td style="text-align: left;"><code>FlightDate</code>, <code>Reporting_Airline</code>, <code>Tail_Number</code>, <code>Origin</code>, <code>Dest</code>, <code>route_key</code>, <code>flight_id</code></td>
<td style="text-align: left;">Core identifiers used to define each flight, link feature tables, and represent route-level context.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Schedule and realized timing</td>
<td style="text-align: left;"><code>CRSDepTime</code>, <code>DepTime</code>, <code>CRSArrTime</code>, <code>ArrTime</code>, <code>dep_ts_sched</code>, <code>dep_ts_actual</code>, <code>arr_ts_sched</code>, <code>arr_ts_actual</code>, UTC timestamp variants</td>
<td style="text-align: left;">Used to represent schedule adherence, construct valid temporal ordering, and support weather joins and aircraft rotation logic.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Delay targets and related operational outcomes</td>
<td style="text-align: left;"><code>ArrDelay</code>, <code>ArrDel15</code>, <code>DepDelay</code>, <code>DepDel15</code>, <code>Cancelled</code>, <code>Diverted</code></td>
<td style="text-align: left;">Primary response variables and closely related operational outputs used in modeling and filtering.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Surface movement and flight characteristics</td>
<td style="text-align: left;"><code>TaxiOut</code>, <code>TaxiIn</code>, <code>Distance</code>, <code>ActualElapsedTime</code></td>
<td style="text-align: left;">Capture operational complexity, congestion effects, and route structure.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Delay cause information</td>
<td style="text-align: left;"><code>CarrierDelay</code>, <code>WeatherDelay</code>, <code>NASDelay</code>, <code>LateAircraftDelay</code></td>
<td style="text-align: left;">Useful for descriptive analysis, route aggregation, and interpretation of operational drivers of delay.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Temporal features</td>
<td style="text-align: left;">Departure hour, weekday, month, local date, UTC date, seasonal indicators, holiday indicators</td>
<td style="text-align: left;">Capture cyclic demand, seasonal traffic patterns, and calendar effects.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Airport reference data</td>
<td style="text-align: left;">Airport name, municipality, country, latitude, longitude, IATA code, ICAO code, airport timezone</td>
<td style="text-align: left;">Used to map BTS airports to weather stations, assign time zones, and support timestamp normalization.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Weather station reference data</td>
<td style="text-align: left;">NOAA station ID, station timezone, airport-to-station mapping</td>
<td style="text-align: left;">Used to associate flights with nearby weather observations and enable correct UTC conversion of NOAA timestamps.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Weather predictors</td>
<td style="text-align: left;"><code>dep_temp_c</code>, <code>dep_wind_speed_m_s</code>, <code>dep_wind_dir_deg</code>, <code>dep_ceiling_height_m</code>, <code>arr_temp_c</code>, <code>arr_wind_speed_m_s</code>, <code>arr_wind_dir_deg</code>, <code>arr_ceiling_height_m</code></td>
<td style="text-align: left;">Represent meteorological conditions associated with the departure and arrival environments. These are joined temporally using the most recent prior observation within a two-hour window.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Aircraft rotation / propagation features</td>
<td style="text-align: left;">Previous flight ID, previous origin and destination, previous arrival delay, previous departure delay, turnaround time, continuity flag, aircraft leg number, cumulative delay by aircraft-day</td>
<td style="text-align: left;">Capture propagation effects caused by late inbound aircraft and tight turnarounds. These were among the most meaningful operational predictors.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Chain and cascade indicators</td>
<td style="text-align: left;"><code>has_prev_leg</code>, <code>has_next_leg</code>, <code>is_middle_leg</code>, tight turnaround flags</td>
<td style="text-align: left;">Represent whether a flight is embedded within a larger aircraft sequence and whether it is vulnerable to upstream or downstream delay propagation.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Airport-time aggregate context</td>
<td style="text-align: left;">Hourly airport flight counts, average delay, median delay, delay rate, cancellation rate, diversion rate, taxi metrics, rolling means over 1h/3h/6h</td>
<td style="text-align: left;">Capture airport congestion and short-horizon system state.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Route-time aggregate context</td>
<td style="text-align: left;">Hourly route counts, mean route delay, route delay rate, average weather, rolling means over 1h/3h/6h</td>
<td style="text-align: left;">Capture recent route-specific operating conditions and network-level delay tendencies.</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
</section>
<section id="limitations-in-data" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="limitations-in-data"><span class="header-section-number">2.3</span> Limitations in Data</h2>
<p>Several limitations should be noted:</p>
<ul>
<li>BTS delay categories are aggregated and sometimes coarse</li>
<li>weather observations may not perfectly represent local flight conditions</li>
<li>route-level analysis cannot capture all national network effects</li>
<li>airline operational decisions such as crew scheduling are not directly observed</li>
</ul>
<p>Despite these limitations, the dataset provides a strong foundation for studying delay patterns.</p>
<ul>
<li>Add catalog as appendix item</li>
</ul>
<p><strong>Note: create a section of the site that represents reproducable instructions of our project and data processing steps, including code snippets and explanations.</strong></p>
</section>
<section id="initially-started-with-a-bwiewr-market-pair" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="initially-started-with-a-bwiewr-market-pair"><span class="header-section-number">2.4</span> Initially started with a BWI–EWR Market Pair</h2>
<p>The BWI–EWR corridor sits within one of the most operationally complex airspaces in the United States. Newark Liberty International Airport operates within the highly congested New York airspace, while BWI serves as a key mid-Atlantic hub.</p>
<p>Flights between these airports are vulnerable to multiple sources of disruption:</p>
<ul>
<li>upstream aircraft delays</li>
<li>weather disruptions</li>
<li>airspace congestion</li>
<li>operational scheduling constraints</li>
</ul>
</section>
</section>
<section id="eda" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> EDA</h1>
<section id="distribution-of-delays" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="distribution-of-delays"><span class="header-section-number">3.1</span> Distribution of Delays</h2>
</section>
<section id="delays-by-time-of-day" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="delays-by-time-of-day"><span class="header-section-number">3.2</span> Delays by Time of Day</h2>
</section>
<section id="weather-vs-delay" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="weather-vs-delay"><span class="header-section-number">3.3</span> Weather vs Delay</h2>
</section>
<section id="delay-propagation-1" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="delay-propagation-1"><span class="header-section-number">3.4</span> Delay Propagation</h2>
</section>
<section id="centrality-metrics" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="centrality-metrics"><span class="header-section-number">3.5</span> Centrality Metrics</h2>
<div class="cell">
<div class="cell-output-display">
<div id="fig-centrality-metrics-airport-bubble" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Centrality Metrics - Airport Bubble">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-centrality-metrics-airport-bubble-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/paper/airport-centrality-bubble.png" class="img-fluid figure-img" style="width:100.0%" alt="Centrality Metrics - Airport Bubble">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-centrality-metrics-airport-bubble-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Centrality Metrics - Airport Bubble
</figcaption>
</figure>
</div>
</div>
</div>
<p>….Otehrs….</p>
<hr>
</section>
</section>
<section id="models" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Models</h1>
<p>We are interested in building an multi-output model that both classifies an arrival delay and determins how long that arrival delay will be using features that are available during the present time.</p>
<section id="phase-1-2019-baseline" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="phase-1-2019-baseline"><span class="header-section-number">4.1</span> Phase 1: 2019 Baseline</h2>
<section id="logistic-regression" class="level3" data-number="4.1.1">
<h3 data-number="4.1.1" class="anchored" data-anchor-id="logistic-regression"><span class="header-section-number">4.1.1</span> Logistic Regression</h3>
<p>We begin with a baseline logistic regression model.</p>
<p><span class="math display">\[
P(Y_i = 1|X_i) =
\frac{1}{1 + e^{-\eta_i}}
\]</span></p>
<p><span class="math display">\[
\eta_i = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + ... + \beta_p X_p
\]</span></p>
</section>
<section id="ridge-logistic-regression" class="level3" data-number="4.1.2">
<h3 data-number="4.1.2" class="anchored" data-anchor-id="ridge-logistic-regression"><span class="header-section-number">4.1.2</span> Ridge Logistic Regression</h3>
<p>To address multicollinearity and improve stability we apply ridge regularization.</p>
</section>
<section id="basic-decision-trees" class="level3" data-number="4.1.3">
<h3 data-number="4.1.3" class="anchored" data-anchor-id="basic-decision-trees"><span class="header-section-number">4.1.3</span> Basic Decision Trees</h3>
<p>Decision trees provide interpretable classification rules.</p>
</section>
<section id="random-forest" class="level3" data-number="4.1.4">
<h3 data-number="4.1.4" class="anchored" data-anchor-id="random-forest"><span class="header-section-number">4.1.4</span> Random Forest</h3>
<p>Random forests improve predictive accuracy through ensemble learning.</p>
</section>
<section id="k-nearest-neighbors" class="level3" data-number="4.1.5">
<h3 data-number="4.1.5" class="anchored" data-anchor-id="k-nearest-neighbors"><span class="header-section-number">4.1.5</span> K-Nearest Neighbors</h3>
<p>KNN classifies flights based on nearby observations in feature space.</p>
</section>
<section id="unsupervised-analysis-principal-component-analysis" class="level3" data-number="4.1.6">
<h3 data-number="4.1.6" class="anchored" data-anchor-id="unsupervised-analysis-principal-component-analysis"><span class="header-section-number">4.1.6</span> Unsupervised Analysis: Principal Component Analysis</h3>
<p>PCA identifies dominant dimensions in the feature space.</p>
</section>
<section id="unsupervised-analysis-k-means-clustering" class="level3" data-number="4.1.7">
<h3 data-number="4.1.7" class="anchored" data-anchor-id="unsupervised-analysis-k-means-clustering"><span class="header-section-number">4.1.7</span> Unsupervised Analysis: K-Means Clustering</h3>
</section>
</section>
<section id="phase-2-multi-year" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="phase-2-multi-year"><span class="header-section-number">4.2</span> Phase 2: Multi Year</h2>
<p>In the final modeling training phase we used all our data. The 10 year run used over 61 million final training records, tuned it with rolling time-aware 5 fold cross-validation across historical years, then evaluated it on a fully unseen 2025 holdout test year containing 6.86 million flights. In total we are working with around 70 million flight records! The following sections will cover the details and how well the models performed.</p>
<section id="hardware" class="level3" data-number="4.2.1">
<h3 data-number="4.2.1" class="anchored" data-anchor-id="hardware"><span class="header-section-number">4.2.1</span> Hardware</h3>
<p>When working with larger data sets models were trained on a local workstation running Ubuntu 22.04.5 LTS (64-bit) with kernel version 6.8. The system is equipped with an AMD Ryzen 9 7900X processor featuring 24 logical cores and boost speeds up to 5.65 GHz, along with approximately 96 GB of system memory. The machine also includes both integrated AMD graphics and a discrete NVIDIA GPU, although model training was mostly conducted using CPU resources and GPU usage on 4 GB of VRAM didn’t yield improved performance. The ML-Pipeline is still configured to run on GPU if desired. This hardware configuration provides substantial parallel processing capability and memory bandwidth, enabling efficient handling of large-scale data processing, feature engineering, and machine learning model training workflows.</p>
</section>
<section id="lstm-spatio-temporal-model" class="level3" data-number="4.2.2">
<h3 data-number="4.2.2" class="anchored" data-anchor-id="lstm-spatio-temporal-model"><span class="header-section-number">4.2.2</span> LSTM Spatio-Temporal Model</h3>
<section id="overview" class="level4" data-number="4.2.2.1">
<h4 data-number="4.2.2.1" class="anchored" data-anchor-id="overview"><span class="header-section-number">4.2.2.1</span> Overview</h4>
<p>A Long Short-Term Memory (LSTM) neural network was developed to model flight delay propagation using sequential aircraft rotation history. Unlike tree-based models that treat each flight independently, the LSTM learns temporal dependencies across prior legs operated by the same tail number — naturally representing how delays cascade through a rotation chain.</p>
<p>For a <strong>2-hop propagation network</strong>, the current flight is conditioned on the two most recent upstream legs:</p>
<p><span class="math display">\[
JFK \rightarrow BOS \rightarrow ATL \rightarrow MIA
\]</span></p>
<p>If the current flight is <span class="math inline">\(ATL \rightarrow MIA\)</span>, then <span class="math inline">\(JFK \rightarrow BOS\)</span> and <span class="math inline">\(BOS \rightarrow ATL\)</span> form its sequential context.</p>
<hr>
</section>
<section id="model-architecture" class="level4" data-number="4.2.2.2">
<h4 data-number="4.2.2.2" class="anchored" data-anchor-id="model-architecture"><span class="header-section-number">4.2.2.2</span> Model Architecture</h4>
<div class="cell">
<div class="cell-output-display">
<div id="fig-lstm" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A diagram of the LSTM model architecture showing a sequential encoder feeding into a classification head and a regression head.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-lstm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/paper/lstm-model.png" class="img-fluid figure-img" style="width:100.0%" alt="A diagram of the LSTM model architecture showing a sequential encoder feeding into a classification head and a regression head.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-lstm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: LSTM architecture for flight delay prediction. The network encodes a 3-timestep aircraft rotation sequence and produces two output heads: a binary delay classifier and a continuous delay regressor.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="input-representation" class="level4" data-number="4.2.2.3">
<h4 data-number="4.2.2.3" class="anchored" data-anchor-id="input-representation"><span class="header-section-number">4.2.2.3</span> Input Representation</h4>
<p>Each flight <span class="math inline">\(i\)</span> is encoded as a 3D sequence tensor:</p>
<p><span class="math display">\[
\mathbf{X}_i \in \mathbb{R}^{T \times F}
\]</span></p>
<p>where <span class="math inline">\(T = 3\)</span> timesteps represent the <strong>previous-2 leg</strong>, <strong>previous-1 leg</strong>, and <strong>current flight context</strong>, and <span class="math inline">\(F\)</span> is the number of engineered features per timestep. Across all training samples the full tensor is:</p>
<p><span class="math display">\[
\mathbf{X} \in \mathbb{R}^{N \times T \times F}
\quad \text{e.g.,} \quad (5{,}000{,}000,\ 3,\ 29)
\]</span></p>
<p>Features at each timestep include prior arrival and departure delays, turnaround gap, distance, time-of-day, weekday, month, weather variables, route frequency, and congestion proxies.</p>
</section>
<section id="preprocessing-and-scaling" class="level4" data-number="4.2.2.4">
<h4 data-number="4.2.2.4" class="anchored" data-anchor-id="preprocessing-and-scaling"><span class="header-section-number">4.2.2.4</span> Preprocessing and Scaling</h4>
<p>Neural networks are sensitive to feature scale. The tensor is temporarily reshaped from <span class="math inline">\((N, T, F)\)</span> to <span class="math inline">\((N \cdot T,\ F)\)</span>, standardised via:</p>
<p><span class="math display">\[
z = \frac{x - \mu}{\sigma}
\]</span></p>
<p>then reshaped back, preserving sequence structure while ensuring stable gradient flow during training.</p>
</section>
<section id="sequence-encoder" class="level4" data-number="4.2.2.5">
<h4 data-number="4.2.2.5" class="anchored" data-anchor-id="sequence-encoder"><span class="header-section-number">4.2.2.5</span> Sequence Encoder</h4>
<p>The LSTM processes each timestep <span class="math inline">\(t\)</span> and updates a hidden state:</p>
<p><span class="math display">\[
\mathbf{h}_t = \text{LSTM}(\mathbf{x}_t,\ \mathbf{h}_{t-1})
\]</span></p>
<p>The final hidden state <span class="math inline">\(\mathbf{h}_T\)</span> serves as a compact representation of the full rotation history and is passed to both output heads. Each LSTM unit learns a temporal pattern from the input sequence; more units increase model capacity at the cost of overfitting risk.</p>
<p>Limiting the network to 2 hops (<span class="math inline">\(T = 3\)</span>) provides a practical guard against exploding gradients, while the LSTM gating mechanism — maintaining separate long-term and short-term memory paths — mitigates the vanishing gradient problem inherent in standard RNNs.</p>
<p>A <strong>dropout rate of 20%</strong> was applied to LSTM outputs during training, randomly deactivating neurons to prevent the model from over-relying on any single feature or pattern.</p>
<hr>
</section>
<section id="multi-task-output-heads" class="level4" data-number="4.2.2.6">
<h4 data-number="4.2.2.6" class="anchored" data-anchor-id="multi-task-output-heads"><span class="header-section-number">4.2.2.6</span> Multi-Task Output Heads</h4>
<p>The shared encoder feeds two independent output heads, enabling simultaneous binary classification and continuous regression from a single forward pass.</p>
</section>
<section id="classification-head" class="level4" data-number="4.2.2.7">
<h4 data-number="4.2.2.7" class="anchored" data-anchor-id="classification-head"><span class="header-section-number">4.2.2.7</span> Classification Head</h4>
<p><span class="math display">\[
\hat{p}_i = \sigma(W_c\, \mathbf{h}_T + b_c)
\]</span></p>
<p>Produces the probability that flight <span class="math inline">\(i\)</span> is delayed by 15 minutes or more.</p>
</section>
<section id="regression-head" class="level4" data-number="4.2.2.8">
<h4 data-number="4.2.2.8" class="anchored" data-anchor-id="regression-head"><span class="header-section-number">4.2.2.8</span> Regression Head</h4>
<p><span class="math display">\[
\hat{y}_i = W_r\, \mathbf{h}_T + b_r
\]</span></p>
<p>Produces the predicted delay in minutes as a continuous value.</p>
<hr>
</section>
<section id="loss-function" class="level4" data-number="4.2.2.9">
<h4 data-number="4.2.2.9" class="anchored" data-anchor-id="loss-function"><span class="header-section-number">4.2.2.9</span> Loss Function</h4>
<p>Both tasks are trained simultaneously using a single combined loss, so the weight updates from backpropagation account for both the classification and regression errors in every pass.</p>
<p><span class="math display">\[
\mathcal{L} = \mathcal{L}_{cls} + \lambda\, \mathcal{L}_{reg}
\]</span></p>
<p>where <span class="math inline">\(\lambda\)</span> balances the contribution of each term. <span class="math inline">\(\lambda\)</span> scales the regression loss so that neither task dominates training, since BCE and MSE naturally operate on different numerical scales.</p>
<p><strong>Classification</strong> uses binary cross-entropy (BCE):</p>
<p><span class="math display">\[
\mathcal{L}_{cls} = -\sum_i \left[ y_i \log(\hat{p}_i) + (1 - y_i)\log(1 - \hat{p}_i) \right]
\]</span></p>
<p>This penalizes confident wrong predictions logarithmically, making it well-suited to binary delay outcomes.</p>
<p><strong>Regression</strong> uses mean squared error (MSE):</p>
<p><span class="math display">\[
\mathcal{L}_{reg} = \sum_i \left( Y_i^{(reg)} - \hat{Y}_i^{(reg)} \right)^2
\]</span></p>
<p>Squaring the residuals penalizes large errors disproportionately, pushing the model to minimize severe mispredictions of delay magnitude.</p>
<hr>
</section>
<section id="limitations-and-model-status" class="level4" data-number="4.2.2.10">
<h4 data-number="4.2.2.10" class="anchored" data-anchor-id="limitations-and-model-status"><span class="header-section-number">4.2.2.10</span> Limitations and Model Status</h4>
<p>Despite its architectural strengths, the LSTM was <strong>dropped from the 10-year training run</strong> due to:</p>
<ul>
<li>Higher memory footprint than gradient-boosted alternatives</li>
<li>Slower training at scale (<span class="math inline">\(N &gt; 5\text{M}\)</span> samples)</li>
<li>Reduced interpretability compared to tree-based models</li>
<li>Non-trivial tensor preparation and scaling pipeline</li>
</ul>
<p>The model is retained in this paper to document its design and to motivate future sequence-based extensions, which may include:</p>
<ul>
<li>Spatio-Temporal Graph Convolutional Networks</li>
<li>Transformer sequence models</li>
<li>Graph Attention Networks</li>
<li>Hybrid LSTM + airport graph embeddings</li>
</ul>
</section>
</section>
<section id="xgboost" class="level3" data-number="4.2.3">
<h3 data-number="4.2.3" class="anchored" data-anchor-id="xgboost"><span class="header-section-number">4.2.3</span> XGBoost</h3>
<p>A tuned Extreme Gradient Boosting (XGBoost) model was developed as the primary predictive model for flight delay forecasting.</p>
<p>XGBoost was selected for this task because gradient-boosted tree ensembles consistently achieve strong performance on large-scale structured tabular data. The method captures nonlinear operational interactions, tolerates heterogeneous feature scales without normalization, and remains computationally tractable at the scale of tens of millions of flight records. Unlike linear models, XGBoost can implicitly model feature interactions such as the combined effect of a tight turnaround window on an already-stressed aircraft — without requiring manual interaction terms.</p>
<p>The full modeling pipeline, from data splitting through final holdout evaluation, is described in the sections that follow.</p>
<section id="data-partitioning-strategy" class="level4" data-number="4.2.3.1">
<h4 data-number="4.2.3.1" class="anchored" data-anchor-id="data-partitioning-strategy"><span class="header-section-number">4.2.3.1</span> Data Partitioning Strategy</h4>
<p>To preserve temporal realism and eliminate any possibility of look-ahead bias, the dataset was partitioned <strong>strictly chronologically</strong>. Future observations were never permitted to influence model training or validation at any stage.</p>
<div id="tbl-splits" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-splits-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Chronological data splits used across the full XGBoost pipeline.
</figcaption>
<div aria-describedby="tbl-splits-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Dataset</th>
<th>Years</th>
<th>Rows</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Training</td>
<td>2015–2023</td>
<td>54,620,695</td>
</tr>
<tr class="even">
<td>Validation</td>
<td>2024</td>
<td>6,947,566</td>
</tr>
<tr class="odd">
<td>Test (Holdout)</td>
<td>2025</td>
<td>6,857,845</td>
</tr>
<tr class="even">
<td><strong>Final Refit Train</strong></td>
<td><strong>2015–2024</strong></td>
<td><strong>61,568,261</strong></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The 2025 holdout set represents completely unseen flight operations and serves as the primary benchmark for reported final performance. No information from 2025 was available at any point during model development, hyperparameter search, or feature selection.</p>
<hr>
</section>
<section id="feature-engineering-1" class="level4" data-number="4.2.3.2">
<h4 data-number="4.2.3.2" class="anchored" data-anchor-id="feature-engineering-1"><span class="header-section-number">4.2.3.2</span> Feature Engineering</h4>
<p>The final feature set for the production model (<code>xgb_full_aircraft</code>) contained <strong>37 predictors</strong> spanning five conceptually distinct categories. Feature selection was guided by domain knowledge of delay propagation mechanisms and validated empirically through cross-validation performance comparisons across feature subsets.</p>
<section id="schedule-and-calendar-features" class="level5" data-number="4.2.3.2.1">
<h5 data-number="4.2.3.2.1" class="anchored" data-anchor-id="schedule-and-calendar-features"><span class="header-section-number">4.2.3.2.1</span> Schedule and Calendar Features</h5>
<p>These features encode when a flight is scheduled, capturing peak-hour congestion effects, weekend travel patterns, holiday demand surges, and seasonal variation.</p>
<ul>
<li><code>distance</code> — great-circle route distance in miles</li>
<li><code>crs_elapsed_time</code> — scheduled block time in minutes</li>
<li><code>dep_hour_local</code> — local departure hour (0–23)</li>
<li><code>dep_weekday_local</code> — day of week (Monday = 0)</li>
<li><code>dep_month_local</code> — calendar month</li>
<li><code>dep_time_bucket</code> — discretized departure time window (e.g., early morning, morning bank, afternoon, evening)</li>
<li><code>is_weekend</code> — binary flag for Saturday/Sunday operations</li>
<li><code>is_holiday</code> — binary flag for federal holiday proximity</li>
<li><code>days_to_nearest_holiday</code> — continuous proximity measure to the nearest holiday</li>
</ul>
</section>
<section id="weather-features" class="level5" data-number="4.2.3.2.2">
<h5 data-number="4.2.3.2.2" class="anchored" data-anchor-id="weather-features"><span class="header-section-number">4.2.3.2.2</span> Weather Features</h5>
<p>Surface weather conditions at both the departure and arrival airports were joined from hourly ASOS/METAR records. Each flight received a pre-departure snapshot at the closest available observation prior to scheduled pushback.</p>
<p>Weather variables included:</p>
<ul>
<li>Temperature (°C)</li>
<li>Wind speed (knots) and direction (degrees)</li>
<li>Visibility (statute miles)</li>
<li>Ceiling height (meters)</li>
<li>Precipitation indicator</li>
</ul>
<p>Example features: <code>dep_temp_c</code>, <code>dep_wind_speed_kt</code>, <code>arr_ceiling_height_m</code>, <code>arr_visibility_sm</code>.</p>
</section>
<section id="network-congestion-features" class="level5" data-number="4.2.3.2.3">
<h5 data-number="4.2.3.2.3" class="anchored" data-anchor-id="network-congestion-features"><span class="header-section-number">4.2.3.2.3</span> Network Congestion Features</h5>
<p>These features quantify operational load at both airports and on the specific route at departure time, capturing system-level congestion independent of any individual aircraft’s history.</p>
<ul>
<li><code>origin_flight_volume</code> — total scheduled departures at origin airport within a rolling time window</li>
<li><code>dest_flight_volume</code> — total scheduled arrivals at destination airport within a rolling time window</li>
<li><code>route_frequency</code> — historical frequency of delays on this origin–destination pair</li>
</ul>
</section>
<section id="aircraft-rotation-state-features" class="level5" data-number="4.2.3.2.4">
<h5 data-number="4.2.3.2.4" class="anchored" data-anchor-id="aircraft-rotation-state-features"><span class="header-section-number">4.2.3.2.4</span> Aircraft Rotation State Features</h5>
<p>These features capture the operational history and physical characteristics of the specific aircraft assigned to the flight. Aircraft continuity — whether the same tail number operated the prior leg — is especially important for modeling mechanical and scheduling carryover.</p>
<ul>
<li><code>aircraft_age</code> — years since aircraft manufacture</li>
<li><code>aircraft_no_eng</code> — number of engines</li>
<li><code>aircraft_no_seats</code> — certified seat capacity</li>
<li><code>aircraft_year_mfr</code> — year of manufacture</li>
<li><code>aircraft_leg_number_day</code> — how many legs the aircraft has already flown today</li>
<li><code>rotation_continuity_flag</code> — whether the inbound leg was operated by the same aircraft</li>
<li><code>relative_leg_position</code> — normalized position of this flight within the aircraft’s daily rotation</li>
</ul>
</section>
<section id="two-hop-upstream-propagation-features" class="level5" data-number="4.2.3.2.5">
<h5 data-number="4.2.3.2.5" class="anchored" data-anchor-id="two-hop-upstream-propagation-features"><span class="header-section-number">4.2.3.2.5</span> Two-Hop Upstream Propagation Features</h5>
<p>The most predictively powerful feature category encodes the delay state of the <strong>same aircraft on its two most recent prior legs</strong>. This two-hop window operationalizes the empirical reality that delays propagate forward through aircraft rotations: a late inbound flight becomes a late outbound flight.</p>
<div id="tbl-propagation" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-propagation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Two-hop upstream propagation features.
</figcaption>
<div aria-describedby="tbl-propagation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Feature</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>prev1_arr_delay</code></td>
<td>Arrival delay (minutes) of the immediately preceding leg</td>
</tr>
<tr class="even">
<td><code>prev1_dep_delay</code></td>
<td>Departure delay (minutes) of the preceding leg</td>
</tr>
<tr class="odd">
<td><code>prev1_arr_del15</code></td>
<td>Binary: was the preceding leg <span class="math inline">\(\geq 15\)</span> min late on arrival?</td>
</tr>
<tr class="even">
<td><code>prev1_dep_del15</code></td>
<td>Binary: was the preceding leg <span class="math inline">\(\geq 15\)</span> min late on departure?</td>
</tr>
<tr class="odd">
<td><code>prev2_arr_delay</code></td>
<td>Arrival delay of the leg two hops prior</td>
</tr>
<tr class="even">
<td><code>prev2_dep_delay</code></td>
<td>Departure delay of the leg two hops prior</td>
</tr>
<tr class="odd">
<td><code>prev2_arr_del15</code></td>
<td>Binary classification of two-hop-prior arrival delay</td>
</tr>
<tr class="even">
<td><code>prev2_dep_del15</code></td>
<td>Binary classification of two-hop-prior departure delay</td>
</tr>
<tr class="odd">
<td><code>prev1_turnaround_minutes</code></td>
<td>Gate time between the inbound aircraft arrival and scheduled next departure</td>
</tr>
<tr class="even">
<td><code>time_since_prev2_arrival_minutes</code></td>
<td>Elapsed time since the aircraft’s second-prior arrival</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Together, these features give the model visibility into the trajectory of delay accumulation along each aircraft’s day, not merely its current scheduled state.</p>
</section>
</section>
</section>
<section id="xgboost-classification-model" class="level3" data-number="4.2.4">
<h3 data-number="4.2.4" class="anchored" data-anchor-id="xgboost-classification-model"><span class="header-section-number">4.2.4</span> XGBoost Classification Model</h3>
<p>The XGBoost classification model estimates the probability that a flight will experience a significant arrival delay:</p>
<p><span class="math display">\[
\hat{p}_i
=
P(Y_i^{(cls)} = 1 \mid \mathbf{x}_i)
=
\sigma\left(
\sum_{m=1}^{M} f_m(\mathbf{x}_i)
\right)
\]</span> where <span class="math inline">\(\sigma(z) = (1 + e^{-z})^{-1}\)</span> and <span class="math inline">\(M = 300\)</span> gradient-boosted trees. where</p>
<p><span class="math display">\[
\sigma(z)=\frac{1}{1+e^{-z}}
\]</span></p>
<p>is the logistic sigmoid function and <span class="math inline">\(M = 300\)</span> gradient-boosted trees. The binary decision rule applies a threshold of 0.5 i.e.&nbsp;the Classification Decision Rule:</p>
<p><span class="math display">\[
\hat{Y}_i^{(cls)} =
\begin{cases}
1 &amp; \text{if } \hat{p}_i \ge 0.5 \\
0 &amp; \text{otherwise}
\end{cases}
\]</span></p>
</section>
<section id="xgboost-regression-model" class="level3" data-number="4.2.5">
<h3 data-number="4.2.5" class="anchored" data-anchor-id="xgboost-regression-model"><span class="header-section-number">4.2.5</span> XGBoost Regression Model</h3>
<p>The XGBoost regression model directly predicts arrival delay in minutes as an additive ensemble of regression trees:</p>
<p><span class="math display">\[
\hat{Y}_i^{(reg)}
=
\sum_{m=1}^{M} g_m(\mathbf{x}_i)
\]</span></p>
<p>At each boosting iteration <span class="math inline">\(t\)</span>, the model minimizes the regularized objective:</p>
<p><span class="math display">\[
\mathcal{L}^{(t)} = \sum_{i=1}^{n} l\!\left(y_i,\, \hat{y}_i^{(t-1)} + f_t(\mathbf{x}_i)\right) + \Omega(f_t)
\]</span></p>
<p>where <span class="math inline">\(l(\cdot)\)</span> is the task-specific loss (log-loss for classification, squared error for regression) and the complexity penalty is:</p>
<p><span class="math display">\[
\Omega(f) = \gamma T + \frac{1}{2}\lambda \sum_{j=1}^{T} w_j^2
\]</span></p>
<p>with <span class="math inline">\(T\)</span> denoting the number of leaves and <span class="math inline">\(w_j\)</span> the leaf weights. This penalty discourages overly complex trees and provides implicit regularization against overfitting on the large but temporally structured dataset.</p>
</section>
</section>
</section>
<section id="model-evaluation-metrics-comparitive-perfromance" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Model Evaluation Metrics &amp; Comparitive Perfromance</h1>
<section id="ml-pipeline" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="ml-pipeline"><span class="header-section-number">5.1</span> ML Pipeline</h2>
<ul>
<li>Add diagram of model training and evaluation process - move to modeling section</li>
<li>Explain what the ML Pipeline is</li>
</ul>
</section>
<section id="time-aware-cross-validation" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="time-aware-cross-validation"><span class="header-section-number">5.2</span> Time-Aware Cross Validation</h2>
<p>Standard random <span class="math inline">\(k\)</span>-fold cross-validation is inappropriate for time-series data because it permits future observations to leak into training folds, producing optimistically biased estimates. Instead, a <strong>rolling-origin expanding-window</strong> cross-validation strategy was employed, where each fold trains on all years up to a cutoff and validates on the immediately following year.</p>
<p><span class="math display">\[
\mathcal{D}_{\text{train}}^{(k)} = \{2015, \ldots, t_k\}, \qquad \mathcal{D}_{\text{val}}^{(k)} = \{t_k + 1\}
\]</span></p>
<p>The five folds used were:</p>
<div id="tbl-cv-folds" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-cv-folds-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: Rolling-origin cross-validation folds.
</figcaption>
<div aria-describedby="tbl-cv-folds-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Fold</th>
<th>Training Years</th>
<th>Validation Year</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>2015–2018</td>
<td>2019</td>
</tr>
<tr class="even">
<td>2</td>
<td>2015–2019</td>
<td>2020</td>
</tr>
<tr class="odd">
<td>3</td>
<td>2015–2020</td>
<td>2021</td>
</tr>
<tr class="even">
<td>4</td>
<td>2015–2021</td>
<td>2022</td>
</tr>
<tr class="odd">
<td>5</td>
<td>2015–2022</td>
<td>2023</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>This design directly simulates production deployment conditions: the model is trained on all available history, then evaluated on the next operational year it has never seen. The expanding window ensures that later folds benefit from more training data, reflecting how a deployed model accumulates history over time.</p>
</section>
<section id="hyperparameter-search" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="hyperparameter-search"><span class="header-section-number">5.3</span> Hyperparameter Search</h2>
<p>A grid search was conducted over four candidate XGBoost configurations, each evaluated using the five-fold rolling cross-validation procedure. The search space covered the primary levers controlling model capacity and regularization:</p>
<ul>
<li>Number of trees (<span class="math inline">\(M\)</span>)</li>
<li>Maximum tree depth (<span class="math inline">\(d\)</span>)</li>
<li>Learning rate (<span class="math inline">\(\eta\)</span>)</li>
<li>Row subsampling ratio (<span class="math inline">\(s\)</span>)</li>
<li>Column subsampling ratio (<span class="math inline">\(c\)</span>)</li>
<li>Minimum child node weight</li>
<li>L2 leaf weight regularization (<span class="math inline">\(\lambda\)</span>)</li>
</ul>
<section id="candidate-configurations" class="level3" data-number="5.3.1">
<h3 data-number="5.3.1" class="anchored" data-anchor-id="candidate-configurations"><span class="header-section-number">5.3.1</span> Candidate Configurations</h3>
<div id="tbl-configs" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-configs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6: Candidate hyperparameter configurations evaluated during grid search.
</figcaption>
<div aria-describedby="tbl-configs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Config</th>
<th>Trees (<span class="math inline">\(M\)</span>)</th>
<th>Depth (<span class="math inline">\(d\)</span>)</th>
<th>LR (<span class="math inline">\(\eta\)</span>)</th>
<th>Subsample (<span class="math inline">\(s\)</span>)</th>
<th>Colsample (<span class="math inline">\(c\)</span>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>xgb_00</code></td>
<td>250</td>
<td>4</td>
<td>0.05</td>
<td>0.8</td>
<td>0.8</td>
</tr>
<tr class="even">
<td><code>xgb_01</code></td>
<td>250</td>
<td>4</td>
<td>0.05</td>
<td>0.8</td>
<td>1.0</td>
</tr>
<tr class="odd">
<td><code>xgb_02</code></td>
<td>300</td>
<td>6</td>
<td>0.05</td>
<td>0.8</td>
<td>0.8</td>
</tr>
<tr class="even">
<td><code>xgb_03</code></td>
<td>400</td>
<td>6</td>
<td>0.03</td>
<td>0.8</td>
<td>0.8</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="selected-configuration" class="level3" data-number="5.3.2">
<h3 data-number="5.3.2" class="anchored" data-anchor-id="selected-configuration"><span class="header-section-number">5.3.2</span> Selected Configuration</h3>
<p>The best-performing configuration was <strong><code>xgb_02</code></strong> (referred to as <code>xgb_03</code> in the production pipeline artifact). Its full parameter set is:</p>
<p><span class="math display">\[
M = 300,\quad d = 6,\quad \eta = 0.05,\quad s = 0.8,\quad c = 0.8
\]</span></p>
<div class="cell">
<div id="tbl-hyperparameters" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-hyperparameters-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;7: Winning XGBoost hyperparameter configuration selected from four candidate configurations.
</figcaption>
<div aria-describedby="tbl-hyperparameters-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Hyperparameter</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">n_estimators</td>
<td style="text-align: right;">300</td>
</tr>
<tr class="even">
<td style="text-align: left;">max_depth</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">learning_rate</td>
<td style="text-align: right;">0.05</td>
</tr>
<tr class="even">
<td style="text-align: left;">subsample</td>
<td style="text-align: right;">0.8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">colsample_bytree</td>
<td style="text-align: right;">0.8</td>
</tr>
<tr class="even">
<td style="text-align: left;">min_child_weight</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">reg_lambda</td>
<td style="text-align: right;">1.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">tree_method</td>
<td style="text-align: right;">hist</td>
</tr>
<tr class="odd">
<td style="text-align: left;">device</td>
<td style="text-align: right;">cpu</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The <code>hist</code> tree method was selected for computational efficiency on the large training dataset. The moderate depth of 6 and conservative learning rate of 0.05 balance model expressiveness with generalization, while subsampling at 80% for both rows and columns introduces stochasticity that reduces variance.</p>
<hr>
</section>
</section>
<section id="cross-validation-performance" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="cross-validation-performance"><span class="header-section-number">5.4</span> Cross-Validation Performance</h2>
<section id="classification-performance-mean-across-5-folds" class="level3" data-number="5.4.1">
<h3 data-number="5.4.1" class="anchored" data-anchor-id="classification-performance-mean-across-5-folds"><span class="header-section-number">5.4.1</span> Classification Performance (Mean Across 5 Folds)</h3>
<div class="cell">
<div id="tbl-cv-classification" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-cv-classification-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;8: Cross-validation classification performance for the selected XGBoost model (xgb_03), mean and approximate standard deviation across 5 rolling folds.
</figcaption>
<div aria-describedby="tbl-cv-classification-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Metric</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">Min</th>
<th style="text-align: right;">Max</th>
<th style="text-align: right;">Approx. SD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">AUC</td>
<td style="text-align: right;">0.8357</td>
<td style="text-align: right;">0.8048</td>
<td style="text-align: right;">0.8525</td>
<td style="text-align: right;">0.0119</td>
</tr>
<tr class="even">
<td style="text-align: left;">F1</td>
<td style="text-align: right;">0.5025</td>
<td style="text-align: right;">0.4122</td>
<td style="text-align: right;">0.5702</td>
<td style="text-align: right;">0.0395</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Precision</td>
<td style="text-align: right;">0.7484</td>
<td style="text-align: right;">0.5696</td>
<td style="text-align: right;">0.8356</td>
<td style="text-align: right;">0.0665</td>
</tr>
<tr class="even">
<td style="text-align: left;">Recall</td>
<td style="text-align: right;">0.3822</td>
<td style="text-align: right;">0.2977</td>
<td style="text-align: right;">0.4548</td>
<td style="text-align: right;">0.0393</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Accuracy</td>
<td style="text-align: right;">0.8714</td>
<td style="text-align: right;">0.8532</td>
<td style="text-align: right;">0.9093</td>
<td style="text-align: right;">0.0140</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="regression-performance-mean-across-5-folds" class="level3" data-number="5.4.2">
<h3 data-number="5.4.2" class="anchored" data-anchor-id="regression-performance-mean-across-5-folds"><span class="header-section-number">5.4.2</span> Regression Performance (Mean Across 5 Folds)</h3>
<div class="cell">
<div id="tbl-cv-regression" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-cv-regression-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;9: Cross-validation regression performance for the selected XGBoost model (xgb_03), mean and approximate standard deviation across 5 rolling folds.
</figcaption>
<div aria-describedby="tbl-cv-regression-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Metric</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">Min</th>
<th style="text-align: right;">Max</th>
<th style="text-align: right;">Approx. SD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">MAE (minutes)</td>
<td style="text-align: right;">18.09</td>
<td style="text-align: right;">17.12</td>
<td style="text-align: right;">18.89</td>
<td style="text-align: right;">0.44</td>
</tr>
<tr class="even">
<td style="text-align: left;">RMSE (minutes)</td>
<td style="text-align: right;">40.86</td>
<td style="text-align: right;">35.07</td>
<td style="text-align: right;">45.49</td>
<td style="text-align: right;">2.61</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Standard deviations are approximated as <span class="math inline">\(\text{SD} \approx (\text{max} - \text{min}) / 4\)</span>, a standard range-based estimate applicable when per-fold values are not stored. These values are conservative lower bounds on true variability.</p>
</div>
</div>
</section>
<section id="interpretation-of-cross-validation-stability" class="level3" data-number="5.4.3">
<h3 data-number="5.4.3" class="anchored" data-anchor-id="interpretation-of-cross-validation-stability"><span class="header-section-number">5.4.3</span> Interpretation of Cross-Validation Stability</h3>
<p>The cross-validation results reveal a model with <strong>strong temporal robustness</strong>. The most discriminative metric — AUC — exhibited the lowest variability (SD = 0.012), indicating that the model’s ability to rank delayed flights above non-delayed flights remained stable across years that spanned a full decade of US aviation operations, including the COVID-19 disruption period (2020–2021) and the subsequent recovery years.</p>
<p>Stability was similarly high for overall accuracy (SD = 0.014) and mean absolute error (SD = 0.44 minutes), confirming that point predictions for delay magnitude did not drift substantially across validation years.</p>
<p>Larger variability in F1 (SD = 0.040), recall (SD = 0.039), and especially precision (SD = 0.067) reflects genuine annual heterogeneity in the delay-event distribution. Pandemic-era years exhibited structurally different delay patterns — reduced traffic volumes but elevated per-flight delay rates in some months — which affected the class-level precision-recall balance without substantially degrading rank-order discrimination. The RMSE variability (SD = 2.61 minutes) similarly reflects the influence of rare, operationally extreme years on tail-error statistics.</p>
<hr>
</section>
</section>
<section id="final-refit-and-holdout-evaluation" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="final-refit-and-holdout-evaluation"><span class="header-section-number">5.5</span> Final Refit and Holdout Evaluation</h2>
<section id="refit-procedure" class="level3" data-number="5.5.1">
<h3 data-number="5.5.1" class="anchored" data-anchor-id="refit-procedure"><span class="header-section-number">5.5.1</span> Refit Procedure</h3>
<p>Following hyperparameter selection, the model was retrained on all pre-test data to maximize the information available for the final deployed model:</p>
<p><span class="math display">\[
\mathcal{D}_{\text{final train}} = \{2015, \ldots, 2024\}
\]</span></p>
<p>The full refit dataset contained <strong>61,568,261 rows</strong>. For memory efficiency during the refit phase, a stratified <strong>35% sample</strong> (21,548,891 rows) was drawn, preserving the class distribution while reducing peak memory requirements. The final model was then evaluated on the completely held-out 2025 dataset.</p>
</section>
<section id="final-holdout-test-results-2025---post-tuning" class="level3" data-number="5.5.2">
<h3 data-number="5.5.2" class="anchored" data-anchor-id="final-holdout-test-results-2025---post-tuning"><span class="header-section-number">5.5.2</span> Final Holdout Test Results (2025) - Post Tuning</h3>
<section id="classification-performance" class="level4" data-number="5.5.2.1">
<h4 data-number="5.5.2.1" class="anchored" data-anchor-id="classification-performance"><span class="header-section-number">5.5.2.1</span> Classification Performance</h4>
<div class="cell">
<div id="tbl-final-classification" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-final-classification-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;10: Final holdout classification performance on unseen 2025 flight operations.
</figcaption>
<div aria-describedby="tbl-final-classification-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Metric</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">AUC</td>
<td style="text-align: right;">0.8452</td>
</tr>
<tr class="even">
<td style="text-align: left;">F1</td>
<td style="text-align: right;">0.5562</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Precision</td>
<td style="text-align: right;">0.8029</td>
</tr>
<tr class="even">
<td style="text-align: left;">Recall</td>
<td style="text-align: right;">0.4254</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Accuracy</td>
<td style="text-align: right;">0.8486</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="regression-performance" class="level4" data-number="5.5.2.2">
<h4 data-number="5.5.2.2" class="anchored" data-anchor-id="regression-performance"><span class="header-section-number">5.5.2.2</span> Regression Performance</h4>
<div class="cell">
<div id="tbl-final-regression" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-final-regression-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;11: Final holdout regression performance on unseen 2025 flight operations.
</figcaption>
<div aria-describedby="tbl-final-regression-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Metric</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">MAE (minutes)</td>
<td style="text-align: right;">20.14</td>
</tr>
<tr class="even">
<td style="text-align: left;">RMSE (minutes)</td>
<td style="text-align: right;">46.17</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>In summary:</p>
<p><span class="math display">\[
\text{AUC} = 0.8452, \quad F_1 = 0.5562, \quad \text{MAE} = 20.14\ \text{min}, \quad \text{RMSE} = 46.17\ \text{min}
\]</span></p>
</section>
</section>
<section id="interpretation-of-final-results" class="level3" data-number="5.5.3">
<h3 data-number="5.5.3" class="anchored" data-anchor-id="interpretation-of-final-results"><span class="header-section-number">5.5.3</span> Interpretation of Final Results</h3>
<p><strong>Discrimination (AUC = 0.845).</strong> The model correctly ranks a randomly selected delayed flight above a randomly selected on-time flight 84.5% of the time on 2025 data. This represents a meaningful improvement over the cross-validation mean AUC of 0.836, suggesting that the model benefited from the expanded 2015–2024 refit training set. An AUC exceeding 0.84 is operationally strong for a binary event as dependent on real-time conditions as flight delay.</p>
<p><strong>Precision (80.3%).</strong> When the model predicts a delay, it is correct more than four times out of five. This high precision makes the model practically useful for triggering downstream operational actions — passenger notifications, gate reassignments, crew advisory alerts — where false alarms carry real cost.</p>
<p><strong>Recall (42.5%).</strong> The model recovers approximately 42.5% of all true delay events at the default 0.5 classification threshold. This relatively conservative recall reflects the class imbalance inherent in flight delay data: on-time flights substantially outnumber delayed flights in the dataset, and the default threshold does not optimize for recall. For use cases requiring higher sensitivity — such as proactive wide-net disruption planning — the decision threshold can be lowered to improve recall at the cost of some precision.</p>
<p><strong>Regression error (MAE = 20.1 min, RMSE = 46.2 min).</strong> The mean absolute prediction error of approximately 20 minutes is reasonable given the inherent unpredictability of delay magnitude, which is influenced by late-breaking weather, ATC decisions, and mechanical events not fully captured in the pre-departure feature window. The substantially higher RMSE reflects the model’s tendency to underestimate severe delays (<span class="math inline">\(&gt;\)</span> 2 hours), consistent with the general difficulty of predicting tail events in heavy-tailed delay distributions.</p>
<hr>
</section>
</section>
<section id="feature-importance-analysis" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="feature-importance-analysis"><span class="header-section-number">5.6</span> Feature Importance Analysis</h2>
<div class="cell">
<div id="tbl-features1" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-features1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;12: Top predictive features by XGBoost gain-based importance score.
</figcaption>
<div aria-describedby="tbl-features1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 5%">
<col style="width: 21%">
<col style="width: 9%">
<col style="width: 63%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Rank</th>
<th style="text-align: left;">Feature</th>
<th style="text-align: right;">Importance</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: left;">prev1_arr_del15</td>
<td style="text-align: right;">0.5106</td>
<td style="text-align: left;">Binary: inbound aircraft arrived ≥ 15 min late (immediate prior leg)</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: left;">prev1_dep_del15</td>
<td style="text-align: right;">0.1247</td>
<td style="text-align: left;">Binary: inbound aircraft departed ≥ 15 min late (immediate prior leg)</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: left;">prev1_arr_delay</td>
<td style="text-align: right;">0.1135</td>
<td style="text-align: left;">Continuous arrival delay in minutes of the immediately prior leg</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: left;">dep_hour_local</td>
<td style="text-align: right;">0.0277</td>
<td style="text-align: left;">Local departure hour of day</td>
</tr>
<tr class="odd">
<td style="text-align: center;">5</td>
<td style="text-align: left;">dep_time_bucket</td>
<td style="text-align: right;">0.0267</td>
<td style="text-align: left;">Discretized departure time window</td>
</tr>
<tr class="even">
<td style="text-align: center;">6</td>
<td style="text-align: left;">prev1_turnaround_minutes</td>
<td style="text-align: right;">0.0262</td>
<td style="text-align: left;">Gate turnaround time between inbound arrival and scheduled next departure</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The feature importance profile is unambiguous: <strong>delay propagation through aircraft rotations is the dominant predictive signal</strong>, accounting for over 75% of total model gain across the top three features alone. The binary flag <code>prev1_arr_del15</code> — whether the inbound leg arrived at least 15 minutes late — contributes over half of all model importance (0.511), confirming that the single most informative question about any outbound flight is: <em>was the same aircraft delayed on its way in?</em></p>
<p>This finding has important operational implications. It validates the two-hop propagation feature engineering strategy and suggests that real-time monitoring of upstream aircraft state is far more valuable for delay prediction than any static schedule or network congestion feature. Schedule timing features (<code>dep_hour_local</code>, <code>dep_time_bucket</code>) appear in the top six but at an order of magnitude less importance than propagation features.</p>
<p>Aircraft metadata variables (<code>aircraft_no_seats</code>, <code>aircraft_year_mfr</code>, <code>aircraft_age</code>, <code>aircraft_no_eng</code>), while individually modest in importance, collectively provided measurable incremental lift in controlled ablation experiments comparing the <code>xgb_full_aircraft</code> feature set to the <code>xgb_2hop_propagation</code> subset alone. This suggests that fleet composition and aircraft utilization patterns carry weak but real signal about delay susceptibility — potentially through maintenance scheduling effects or route assignment patterns associated with specific aircraft types.</p>
<hr>
</section>
<section id="feature-set-comparison" class="level2" data-number="5.7">
<h2 data-number="5.7" class="anchored" data-anchor-id="feature-set-comparison"><span class="header-section-number">5.7</span> Feature Set Comparison</h2>
<p>To isolate the contribution of each feature category, four nested feature configurations were evaluated under identical cross-validation conditions:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Feature Set</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>xgb_schedule</code></td>
<td>Schedule and calendar features only</td>
</tr>
<tr class="even">
<td><code>xgb_context</code></td>
<td>Schedule + weather + network congestion</td>
</tr>
<tr class="odd">
<td><code>xgb_2hop_propagation</code></td>
<td>All features except aircraft metadata</td>
</tr>
<tr class="even">
<td><code>xgb_full_aircraft</code></td>
<td>Complete 37-feature set including aircraft metadata</td>
</tr>
</tbody>
</table>
<p>The fully enriched <code>xgb_full_aircraft</code> model was the best overall performer across both classification and regression metrics, confirming that each feature category contributes incrementally. The largest single performance gain was observed when two-hop propagation features were added to the context feature set, consistent with their dominant importance scores. Aircraft metadata provided a smaller but consistent additional improvement.</p>
<hr>
</section>
<section id="computational-performance" class="level2" data-number="5.8">
<h2 data-number="5.8" class="anchored" data-anchor-id="computational-performance"><span class="header-section-number">5.8</span> Computational Performance</h2>
<p>The complete XGBoost pipeline — encompassing data loading, FAA registry enrichment, rolling cross-validation across five folds, hyperparameter evaluation across four configurations, final refit, and artifact generation — completed in approximately <strong>1,035 seconds (~17.3 minutes)</strong> on CPU hardware using 8 parallel worker cores.</p>
<p>This compares favorably against deep learning alternatives (e.g., LSTM-based models requiring GPU hardware and substantially longer training times) and demonstrates that XGBoost remains a practical choice for production-scale aviation delay forecasting without specialized compute infrastructure.</p>
<hr>
</section>
<section id="model-comparison" class="level2" data-number="5.9">
<h2 data-number="5.9" class="anchored" data-anchor-id="model-comparison"><span class="header-section-number">5.9</span> Model Comparison</h2>
<div class="cell">
<div class="cell-output-display">
<div id="fig-auc-model-compare" class="quarto-float quarto-figure quarto-figure-center anchored" alt="ROC curves for model varients on the 2025 holdout evaluation set - Before Tuning.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-auc-model-compare-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/paper/roc-final.png" class="img-fluid figure-img" style="width:100.0%" alt="ROC curves for model varients on the 2025 holdout evaluation set - Before Tuning.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-auc-model-compare-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: ROC curves for model varients on the 2025 holdout evaluation set - Before Tuning.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-regression-metrics-compare" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Regression metrics for model varients on the 2025 holdout evaluation set - Before Tuning.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-regression-metrics-compare-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/paper/regression-metrics-overlay.png" class="img-fluid figure-img" style="width:100.0%" alt="Regression metrics for model varients on the 2025 holdout evaluation set - Before Tuning.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-regression-metrics-compare-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Regression metrics for model varients on the 2025 holdout evaluation set - Before Tuning.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-actual-v-pred-model-compare" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Actual versus predicted delay for the xgb_full_aircraft model on the 2025 holdout evaluation set - Before Tuning.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-actual-v-pred-model-compare-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/paper/actuals-v-projects-final.png" class="img-fluid figure-img" style="width:100.0%" alt="Actual versus predicted delay for the xgb_full_aircraft model on the 2025 holdout evaluation set - Before Tuning.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-actual-v-pred-model-compare-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: Actual versus predicted delay for the xgb_full_aircraft model on the 2025 holdout evaluation set - Before Tuning.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="summary" class="level2" data-number="5.10">
<h2 data-number="5.10" class="anchored" data-anchor-id="summary"><span class="header-section-number">5.10</span> Summary</h2>
<p>The tuned XGBoost model achieved strong predictive performance on completely unseen 2025 US domestic flight operations after hyper parameter tuning:</p>
<p><span class="math display">\[
\text{AUC} = 0.845, \quad F_1 = 0.556, \quad \text{Precision} = 0.803, \quad \text{MAE} = 20.1\ \text{min}
\]</span></p>
<p>The results confirm that <strong>aircraft rotation propagation is the primary mechanism underlying flight delay formation</strong> at the national scale: the single most predictive feature — whether the same aircraft arrived late on its immediately prior leg — contributed over 50% of total model gain. Schedule, weather, and network congestion features provided meaningful secondary signal, while aircraft metadata added modest but consistent incremental improvement.</p>
<p>The rolling-origin cross-validation strategy yielded stable performance estimates across five temporal folds spanning a decade of operational history, with low AUC variance (SD = 0.012) confirming that the model learned transferable patterns rather than overfitting to any particular year’s conditions.</p>
<p>Overall, XGBoost proved to be a computationally efficient, highly interpretable, and production-ready modeling approach for large-scale national flight delay prediction, providing a strong baseline against which more complex sequential architectures may be compared.</p>
<hr>
</section>
<section id="operational-impact" class="level2" data-number="5.11">
<h2 data-number="5.11" class="anchored" data-anchor-id="operational-impact"><span class="header-section-number">5.11</span> Operational Impact</h2>
<p>Translating model performance metrics into operational terms requires applying the holdout classification results to the scale of actual flight operations. The 2025 holdout set contained <strong>6,857,845 flight records</strong>, of which approximately <strong>23.4%</strong> were labeled as delayed (<span class="math inline">\(\texttt{ArrDel15} = 1\)</span>), yielding roughly <strong>1,604,736 true delay events</strong> in the evaluation period.</p>
<p>At the default threshold of 0.50, the model’s precision of 0.803 and recall of 0.425 imply the following approximate operational outcomes across the holdout year:</p>
<div class="cell">
<div id="tbl-operational-impact" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-operational-impact-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;13: Approximate annual operational outcomes at the default threshold (0.50), derived from 2025 holdout classification results.
</figcaption>
<div aria-describedby="tbl-operational-impact-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 41%">
<col style="width: 18%">
<col style="width: 41%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Outcome</th>
<th style="text-align: right;">Approximate Count</th>
<th style="text-align: left;">Note</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Total flights evaluated</td>
<td style="text-align: right;">6,857,845</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">True delay events (actual)</td>
<td style="text-align: right;">~1,604,736</td>
<td style="text-align: left;">23.4% base delay rate</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Delay alerts issued (predicted positive)</td>
<td style="text-align: right;">~851,468</td>
<td style="text-align: left;">Precision × TP + FP</td>
</tr>
<tr class="even">
<td style="text-align: left;">Correct alerts — True Positives</td>
<td style="text-align: right;">~681,613</td>
<td style="text-align: left;">Recall × true delay events</td>
</tr>
<tr class="odd">
<td style="text-align: left;">False alerts — False Positives</td>
<td style="text-align: right;">~166,951</td>
<td style="text-align: left;">Correctly flagged but flight was on time</td>
</tr>
<tr class="even">
<td style="text-align: left;">Missed delays — False Negatives</td>
<td style="text-align: right;">~923,123</td>
<td style="text-align: left;">Delayed flights the model did not flag</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Correct non-alerts — True Negatives</td>
<td style="text-align: right;">~5,086,158</td>
<td style="text-align: left;">On-time flights correctly left unflagged</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Counts are derived from reported precision (0.803) and recall (0.425) applied to the approximate true delay count. Verify against your confusion matrix outputs for exact figures.</p>
</div>
</div>
<p>(REVIEW THIS SECTION - What is here is just an example)</p>
<p>Several operational implications follow directly from these numbers.</p>
<p><strong>Scale of actionable intelligence.</strong> The model issues approximately <strong>851,000 delay alerts annually</strong> — roughly 2,330 per day across the national network — of which over <strong>680,000 are correct</strong>. At this scale, even a modest per-alert value (e.g., $50 in avoided passenger reaccommodation costs or crew repositioning savings) implies substantial aggregate operational value.</p>
<p><strong>Cost of false alarms.</strong> Approximately <strong>167,000 false alerts</strong> are issued annually. The operational cost of each false alarm depends on what action it triggers. For low-cost interventions such as informational passenger notifications, false alarm costs are minimal. For high-cost actions such as preemptive aircraft swaps, the false alarm rate justifies threshold adjustment upward toward 0.70 (see <strong>?@tbl-threshold-sweep</strong>).</p>
<p><strong>Scale of missed delays.</strong> The model misses approximately <strong>923,000 true delay events</strong> annually — delays that occur without a prior model alert. The majority of these are likely short delays (15–30 minutes) driven by factors not well represented in pre-departure features, such as late ATC clearances or gate conflicts. A recall-optimized threshold would reduce this number at the cost of additional false alarms.</p>
<p><strong>Regression precision in context.</strong> A mean absolute prediction error of 20.1 minutes, applied across the approximately 681,000 correctly identified delay events, means the model’s delay magnitude estimates are typically within one connection window of the true delay. For airports with 30-minute minimum connection times, a 20-minute MAE is operationally meaningful for rebooking triage.</p>
<p>These figures underscore that the model is not a laboratory artifact — at national scale, even imperfect predictions at this precision level represent a substantial operational information advantage over uninformed scheduling assumptions.</p>
</section>
<section id="model-limitations" class="level2" data-number="5.12">
<h2 data-number="5.12" class="anchored" data-anchor-id="model-limitations"><span class="header-section-number">5.12</span> Model Limitations</h2>
<p>The 2-hop propagation framework was designed to capture delay carryover from the two most recent upstream aircraft legs. This was a practical and computationally efficient approximation of delay dynamics: While highly useful, this design imposes important structural limitations for both LSTM and XGBoost model approaches.</p>
<p>(REVIEW)</p>
<ul>
<li>Core Limitation: Finite Memory Window. The 2-hop model only observes two upstream legs.</li>
<li>Hidden Accumulated Operational Stress. Aircraft systems often degrade gradually throughout the day.</li>
<li>Same-Aircraft Only Perspective.</li>
<li>The propagation design centered on aircraft tail-number continuity:</li>
<li>No Explicit Airport Network Topology. The 2-hop model does not explicitly represent the airport graph:</li>
<li>XGBoost can model nonlinear interactions, but it does not maintain hidden recurrent state.</li>
<li>Feature Explosion Risk. As hops increase the feature space grows rapidly.</li>
<li>Temporal Leakage Risk. Both approaches must ensure upstream features are truly available before prediction time.</li>
</ul>
<hr>
</section>
</section>
<section id="discussion" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Discussion</h1>
<p>(REVIEW &amp; ADD MORE)</p>
<hr>
</section>
<section id="conclusion" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Conclusion</h1>
<p>(REVIEW &amp; ADD MORE)</p>
<p>This study demonstrates how machine learning methods can be applied to understand delay dynamics…</p>
<p>Future work could extend this framework to larger airline networks and incorporate time-series modeling approaches…..etc.</p>
<hr>
</section>
<section id="appendex" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Appendex</h1>
<section id="introduction-to-aeroflux-real-time-inference-for-flight-delay-prediction" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="introduction-to-aeroflux-real-time-inference-for-flight-delay-prediction"><span class="header-section-number">8.1</span> Introduction to AeroFlux: Real-Time Inference for Flight Delay Prediction</h2>
<p>AeroFlux is a predictive intelligence system for U.S. domestic flight delays. Given a specific flight — identified by tail number, date, origin, and destination — it predicts whether that flight will arrive more than 15 minutes late and estimates the total delay in minutes.</p>
<p>Rather than treating each flight in isolation, AeroFlux models the full operational history of the aircraft: the two preceding legs, their on-time performance, turnaround time, cumulative delay buildup over the course of the day, and weather conditions at departure. This context-aware approach captures the cascading nature of flight delays in ways that single-flight models cannot.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-aeroflux1" class="quarto-float quarto-figure quarto-figure-center anchored" alt="AeroFlux predictive intelligence system user interface">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-aeroflux1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/aero-flux/app_v2.png" class="img-fluid figure-img" style="width:100.0%" alt="AeroFlux predictive intelligence system user interface">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-aeroflux1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8: AeroFlux predictive intelligence system user interface
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-aeroflux2" class="quarto-float quarto-figure quarto-figure-center anchored" alt="AeroFlux Flight Map">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-aeroflux2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/aero-flux/flight-map-app_v2.png" class="img-fluid figure-img" style="width:100.0%" alt="AeroFlux Flight Map">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-aeroflux2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9: AeroFlux Flight Map
</figcaption>
</figure>
</div>
</div>
</div>
<section id="aeroflux-is-the-precursor-to-a-digital-twin" class="level3" data-number="8.1.1">
<h3 data-number="8.1.1" class="anchored" data-anchor-id="aeroflux-is-the-precursor-to-a-digital-twin"><span class="header-section-number">8.1.1</span> AeroFlux is the precursor to a digital twin</h3>
<p>AeroFlux is not yet a digital twin but will soon be one. A true digital twin would ingest live operational data in real time, continuously update its state, and support simulation — answering questions like <em>what happens to the next four flights on this tail if this departure slips 45 minutes?</em></p>
<p>AeroFlux is the immediate precursor. The machine learning pipeline, feature engineering, model inference layer, and interactive interface are all in place. What it currently lacks is the live data feed connecting it to real-time flight state. That connection is the primary objective for the next phase of development. The progression looks like this:</p>
<ul>
<li><p><strong>Phase 1 — Historical Proof of Concept</strong> <em>(complete)</em> Baseline models trained, data and ML pipelines built, and an interactive prototype deployed. The foundation is in place: a working system that can ingest flight records, engineer operational context features, and produce interpretable delay predictions.</p></li>
<li><p><strong>Phase 2 — Live Data &amp; Comprehensive Modeling</strong> <em>(next)</em> Connect to FAA or a commercial flight data API to replace historical lookups with real-time inference. Layer in live weather and social media feeds, and research more robust modeling architectures that better capture spatial-temporal dependencies across a flight day. Enhancing the UI with beautiful data visualizations.</p></li>
<li><p><strong>Phase 3 — Network Simulation</strong> Using Rust as a high-performance simulation engine, propagate predicted delays forward through the full rotation chain. Model downstream passenger connections, gate conflicts, and crew constraints — shifting AeroFlux from a single-flight predictor into a network-aware reasoning system.</p></li>
<li><p><strong>Phase 4 — Digital Twin</strong> A continuously updated, bidirectional model of the entire U.S. domestic flight network. Full scenario simulation: what happens to 400 downstream flights if a hub goes offline? What’s the optimal recovery sequence after a ground stop? AeroFlux becomes a live mirror of the national airspace.</p></li>
<li><p><strong>Beyond Phase 4 — The Intelligent Orchestration Layer</strong> This is where AeroFlux transcends flight delays entirely and becomes a framework for reasoning about any system of moving objects in physical space. The ability to model intent, predict state, and propagate consequences through a network of interdependent agents is one of the most valuable capabilities in safety-critical systems — and nowhere is this more consequential than in avionics. Air Traffic Control operates at the edge of human cognitive limits, managing hundreds of aircraft simultaneously with razor-thin margins for error. A system that can anticipate conflicts before they materialize, surface the highest-risk situations in real time, and suggest resolution paths doesn’t just improve efficiency — it fundamentally changes the error surface, shifting ATC from reactive management to proactive orchestration.</p></li>
</ul>
<p>The architecture — real-time telemetry ingestion, predictive state modeling, network propagation, and scenario simulation — maps directly onto adjacent domains: urban air mobility fleets of autonomous air taxis, drone delivery networks optimizing thousands of concurrent last-mile routes, autonomous vehicle coordination across highway and urban grids, maritime vessel scheduling through congested port corridors, and satellite constellation management.</p>
<p><a href="./aero-flux.html">See AeroFlux here</a></p>
<p><a href="https://aeroflux.duckdns.org/">Official AeroFlux App</a> - Note: this domain might change in the future. If this happens notify the authors for more information.</p>




</section>
</section>
</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body" data-entry-spacing="0" role="list">
<div id="ref-usafacts_ontime" class="csl-entry" role="listitem">
<div class="csl-left-margin">[1] </div><div class="csl-right-inline">USAFacts Team, <span>“What are the best and worst airports and airlines for on-time performance?”</span> <a href="https://usafacts.org/articles/what-are-the-best-and-worst-airlines-for-on-time-performance/" class="uri">https://usafacts.org/articles/what-are-the-best-and-worst-airlines-for-on-time-performance/</a>; USAFacts, 2025.</div>
</div>
<div id="ref-people_delayed_airline" class="csl-entry" role="listitem">
<div class="csl-left-margin">[2] </div><div class="csl-right-inline">People Staff, <span>“The world’s most delayed airline in 2025 might surprise travelers.”</span> <a href="https://people.com/the-world-s-most-delayed-airline-in-2025-might-surprise-travelers-11870658" class="uri">https://people.com/the-world-s-most-delayed-airline-in-2025-might-surprise-travelers-11870658</a>; People, 2025.</div>
</div>
<div id="ref-skyrefund_ustravel" class="csl-entry" role="listitem">
<div class="csl-left-margin">[3] </div><div class="csl-right-inline">SkyRefund, <span>“SkyRefund analysis reveals US travelers lost 1.5 million hours to flight delays in 2025 — and what caused them.”</span> <a href="https://www.prnewswire.com/news-releases/skyrefund-analysis-reveals-us-travelers-lost-1-5-million-hours-to-flight-delays-in-2025--and-what-caused-them-302675101.html" class="uri">https://www.prnewswire.com/news-releases/skyrefund-analysis-reveals-us-travelers-lost-1-5-million-hours-to-flight-delays-in-2025--and-what-caused-them-302675101.html</a>; PR Newswire, Jan. 2026.</div>
</div>
<div id="ref-Fleurquin_2013" class="csl-entry" role="listitem">
<div class="csl-left-margin">[4] </div><div class="csl-right-inline">P. Fleurquin, J. J. Ramasco, and V. M. Eguiluz, <span>“Systemic delay propagation in the US airport network,”</span> <em>Scientific Reports</em>, vol. 3, no. 1, Jan. 2013, doi: <a href="https://doi.org/10.1038/srep01159">10.1038/srep01159</a>.</div>
</div>
<div id="ref-zhou2025integratingdelayabsorptioncapabilityflight" class="csl-entry" role="listitem">
<div class="csl-left-margin">[5] </div><div class="csl-right-inline">J. Zhou, <span>“Integrating delay-absorption capability into flight departure delay prediction.”</span> 2025. Available: <a href="https://arxiv.org/abs/2512.08197">https://arxiv.org/abs/2512.08197</a></div>
</div>
<div id="ref-bts_ontime" class="csl-entry" role="listitem">
<div class="csl-left-margin">[6] </div><div class="csl-right-inline">Bureau of Transportation Statistics, <span>“Airline on-time performance data.”</span> <a href="https://transtats.bts.gov/" class="uri">https://transtats.bts.gov/</a>; U.S. Department of Transportation, 2025.</div>
</div>
<div id="ref-rebollo2014predictability" class="csl-entry" role="listitem">
<div class="csl-left-margin">[7] </div><div class="csl-right-inline">J. J. Rebollo and H. Balakrishnan, <span>“Characterization and prediction of air traffic delays,”</span> <em>Transportation Research Part C</em>, vol. 44, pp. 231–241, 2014.</div>
</div>
<div id="ref-li2016delay" class="csl-entry" role="listitem">
<div class="csl-left-margin">[8] </div><div class="csl-right-inline">J. Li, N. Chen, and J. Zhang, <span>“Modeling and simulation of flight delay propagation based on complex networks,”</span> <em>Physica A</em>, vol. 444, pp. 102–112, 2016.</div>
</div>
<div id="ref-chen2016xgboost" class="csl-entry" role="listitem">
<div class="csl-left-margin">[9] </div><div class="csl-right-inline">T. Chen and C. Guestrin, <span>“XGBoost: A scalable tree boosting system,”</span> <em>Proceedings of the ACM SIGKDD</em>, 2016.</div>
</div>
<div id="ref-hochreiter1997lstm" class="csl-entry" role="listitem">
<div class="csl-left-margin">[10] </div><div class="csl-right-inline">S. Hochreiter and J. Schmidhuber, <span>“Long short-term memory,”</span> <em>Neural Computation</em>, vol. 9, no. 8, pp. 1735–1780, 1997.</div>
</div>
<div id="ref-grinsztajn2022tree" class="csl-entry" role="listitem">
<div class="csl-left-margin">[11] </div><div class="csl-right-inline">L. Grinsztajn, E. Oyallon, and G. Varoquaux, <span>“Why do tree-based models still outperform deep learning on tabular data?”</span> in <em>Advances in neural information processing systems (NeurIPS)</em>, 2022. Available: <a href="https://arxiv.org/abs/2207.08815">https://arxiv.org/abs/2207.08815</a></div>
</div>
<div id="ref-zhao2020gnn_airtraffic" class="csl-entry" role="listitem">
<div class="csl-left-margin">[12] </div><div class="csl-right-inline"><span class="nocase">L. Zhao <em>et al.</em></span>, <span>“Graph neural networks for air traffic flow prediction,”</span> <em>IEEE Access</em>, vol. 8, pp. 134984–134994, 2020.</div>
</div>
<div id="ref-yu2018stgcn" class="csl-entry" role="listitem">
<div class="csl-left-margin">[13] </div><div class="csl-right-inline">B. Yu, H. Yin, and Z. Zhu, <span>“Spatio-temporal graph convolutional networks: A deep learning framework for traffic forecasting,”</span> in <em>Proceedings of the 27th international joint conference on artificial intelligence (IJCAI)</em>, AAAI Press, 2018, pp. 3634–3640.</div>
</div>
<div id="ref-vos2024transformer_airtraffic" class="csl-entry" role="listitem">
<div class="csl-left-margin">[14] </div><div class="csl-right-inline">R. W. Vos, J. Sun, and J. M. Hoekstra, <span>“A transformer-based trajectory prediction model to support air traffic demand forecasting,”</span> in <em>Proceedings of the international conference on research in air transportation (ICRAT)</em>, 2024.</div>
</div>
<div id="ref-airtraffic_transformer_flow" class="csl-entry" role="listitem">
<div class="csl-left-margin">[15] </div><div class="csl-right-inline"><span>“Air traffic flow representation and prediction using transformer neural networks,”</span> in <em>SESAR innovation days</em>, 2022.</div>
</div>
<div id="ref-yoon2025maiformer" class="csl-entry" role="listitem">
<div class="csl-left-margin">[16] </div><div class="csl-right-inline">S. Yoon and K. Lee, <span>“MAIFormer: Multi-agent inverted transformer for flight trajectory prediction,”</span> <em>arXiv preprint arXiv:2509.21004</em>, 2025.</div>
</div>
<div id="ref-tao2019digitaltwin" class="csl-entry" role="listitem">
<div class="csl-left-margin">[17] </div><div class="csl-right-inline">F. Tao and M. Zhang, <span>“Digital twin shop-floor: A new shop-floor paradigm towards smart manufacturing,”</span> <em>IEEE Access</em>, vol. 7, pp. 7427–7438, 2019.</div>
</div>
<div id="ref-fuller2020digital" class="csl-entry" role="listitem">
<div class="csl-left-margin">[18] </div><div class="csl-right-inline">A. Fuller, Z. Fan, C. Day, and C. Barlow, <span>“Digital twin: Enabling technologies, challenges and open research,”</span> <em>IEEE Access</em>, vol. 8, pp. 108952–108971, 2020.</div>
</div>
<div id="ref-faa_swim" class="csl-entry" role="listitem">
<div class="csl-left-margin">[19] </div><div class="csl-right-inline">Federal Aviation Administration, <span>“System wide information management (SWIM).”</span> <a href="https://www.faa.gov/air_traffic/technology/swim" class="uri">https://www.faa.gov/air_traffic/technology/swim</a>, 2025.</div>
</div>
<div id="ref-nasa_nas_twin" class="csl-entry" role="listitem">
<div class="csl-left-margin">[20] </div><div class="csl-right-inline">NASA Ames Research Center, <span>“Digital twin simulator of the national airspace system (NAS).”</span> <a href="https://technology.nasa.gov/patent/TOP2-325" class="uri">https://technology.nasa.gov/patent/TOP2-325</a>; NASA, 2024.</div>
</div>
<div id="ref-asi_flyways" class="csl-entry" role="listitem">
<div class="csl-left-margin">[21] </div><div class="csl-right-inline">Airspace Intelligence, <span>“Flyways <span>AI</span>: Air traffic management platform.”</span> <a href="https://www.airspace-intelligence.com/solutions/air-traffic-management" class="uri">https://www.airspace-intelligence.com/solutions/air-traffic-management</a>; Airspace Intelligence, 2025.</div>
</div>
<div id="ref-mosaicatm_arat" class="csl-entry" role="listitem">
<div class="csl-left-margin">[22] </div><div class="csl-right-inline">M. Rodriguez, <span>“Using real-time data and machine learning to improve air traffic management operations.”</span> <a href="https://mosaicatm.com/2024/12/16/machine-learning-for-air-traffic-management/" class="uri">https://mosaicatm.com/2024/12/16/machine-learning-for-air-traffic-management/</a>; Mosaic ATM, Dec. 2024.</div>
</div>
<div id="ref-liu2024digitaltwin" class="csl-entry" role="listitem">
<div class="csl-left-margin">[23] </div><div class="csl-right-inline"><span class="nocase">Liu <em>et al.</em></span>, <span>“Digital twin-enabled delay diagnosis traceability and propagation process for airport flight ground service,”</span> <em>International Journal of Intelligent Systems</em>, 2024, doi: <a href="https://doi.org/10.1155/int/7458758">10.1155/int/7458758</a>.</div>
</div>
<div id="ref-noaa_ncei" class="csl-entry" role="listitem">
<div class="csl-left-margin">[24] </div><div class="csl-right-inline">National Oceanic and Atmospheric Administration, <span>“NCEI access services API: Global hourly weather dataset.”</span> <a href="https://www.ncei.noaa.gov/access/services/data/v1" class="uri">https://www.ncei.noaa.gov/access/services/data/v1</a>; NOAA National Centers for Environmental Information, 2025.</div>
</div>
<div id="ref-noaa_isd_history" class="csl-entry" role="listitem">
<div class="csl-left-margin">[25] </div><div class="csl-right-inline">National Oceanic and Atmospheric Administration, <span>“Integrated surface database (ISD) station history metadata file.”</span> <a href="https://www.ncei.noaa.gov/pub/data/noaa/isd-history.csv" class="uri">https://www.ncei.noaa.gov/pub/data/noaa/isd-history.csv</a>; NOAA National Centers for Environmental Information, 2025.</div>
</div>
<div id="ref-ourairports" class="csl-entry" role="listitem">
<div class="csl-left-margin">[26] </div><div class="csl-right-inline">OurAirports, <span>“OurAirports global airport database.”</span> <a href="https://davidmegginson.github.io/ourairports-data/airports.csv" class="uri">https://davidmegginson.github.io/ourairports-data/airports.csv</a>; OurAirports, 2025.</div>
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/jonathanwilsonami\.github\.io\/OR568_ML_Project\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>